// packages/csc-ui-documentation-next/app/examples/c-text-field/textarea.react.tsx
// @ts-nocheck — documentation code sample; shown as text, never compiled here
import { useState } from 'react';
import { CTextField } from '@cscfi/csc-ui-next-react';

export const Textarea = () => {
  const [description, setDescription] = useState('');

  return (
    <div>
      <CTextField
        value={description}
        hint="A rows value above 1 renders a textarea"
        label="Description"
        rows={4}
        onChangeValue={(event) => setDescription(event.detail as string)}
      />
    </div>
  );
};

// packages/csc-ui-documentation-next/app/examples/c-text-field/textarea.vue
<template>
  <div>
    <c-text-field
      :value="description"
      hint="A rows value above 1 renders a textarea"
      label="Description"
      rows="4"
      @changeValue="onChange"
    />
  </div>
</template>

<script setup lang="ts">
const description = ref('');

const onChange = (event: Event) => {
  description.value = (event as CustomEvent<string>).detail;
};
</script>
