// packages/csc-ui/documentation/angular/src/app/examples/c-accordion/c-accordion.component.ts
import { Component, OnInit } from '@angular/core';
import { mdiAccessPoint, mdiCamera, mdiNas } from '@mdi/js';

@Component({
  selector: 'app-c-accordion',
  templateUrl: './c-accordion.component.html',
  styleUrls: ['./c-accordion.component.scss'],
})
export class CAccordionComponent implements OnInit {
  constructor() {}

  mdiAccessPoint = mdiAccessPoint;

  mdiNas = mdiNas;

  mdiCamera = mdiCamera;

  ngOnInit(): void {}
}

<app-example title="Default" component="c-accordion" name="basic" rows>
  <c-accordion value="one">
    <c-accordion-item heading="One" value="one">
      <c-icon [path]="mdiAccessPoint" slot="icon"></c-icon>
      Lorem ipsum dolor sit amet.
    </c-accordion-item>
    <c-accordion-item heading="Two" value="two">
      <c-icon [path]="mdiNas" slot="icon"></c-icon>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, perspiciatis?
    </c-accordion-item>
    <c-accordion-item heading="Three" value="three">
      <c-icon [path]="mdiCamera" slot="icon"></c-icon>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia voluptatum perspiciatis
      itaque!
    </c-accordion-item>
  </c-accordion>
</app-example>

<app-example
  title="Mandatory selection"
  subtitle="One expanded panel is required"
  component="c-accordion"
  name="mandatory"
  rows
>
  <c-accordion value="one" mandatory>
    <c-accordion-item heading="One" value="one">
      <c-icon [path]="mdiAccessPoint" slot="icon"></c-icon>
      Lorem ipsum dolor sit amet.
    </c-accordion-item>
    <c-accordion-item heading="Two" value="two">
      <c-icon [path]="mdiNas" slot="icon"></c-icon>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, perspiciatis?

      <c-text-field placeholder="Text field within the accordion item"></c-text-field>
    </c-accordion-item>
    <c-accordion-item heading="Three" value="three">
      <c-icon [path]="mdiCamera" slot="icon"></c-icon>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia voluptatum perspiciatis
      itaque!
    </c-accordion-item>
  </c-accordion>
</app-example>

<app-example title="Multiple" component="c-accordion" name="multiple" rows>
  <c-accordion [value]="['one', 'three']" multiple>
    <c-accordion-item heading="One" value="one">
      <c-icon [path]="mdiAccessPoint" slot="icon"></c-icon>
      Lorem ipsum dolor sit amet.
    </c-accordion-item>
    <c-accordion-item heading="Two" value="two">
      <c-icon [path]="mdiNas" slot="icon"></c-icon>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, perspiciatis?
    </c-accordion-item>
    <c-accordion-item heading="Three" value="three">
      <c-icon [path]="mdiCamera" slot="icon"></c-icon>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia voluptatum perspiciatis
      itaque!
    </c-accordion-item>
  </c-accordion>
</app-example>

<app-example title="Outlined items" component="c-accordion" name="outlined" rows>
  <c-accordion value="three" outlined>
    <c-accordion-item heading="One" value="one">
      <c-icon [path]="mdiAccessPoint" slot="icon"></c-icon>
      Lorem ipsum dolor sit amet.
    </c-accordion-item>
    <c-accordion-item heading="Two" value="two">
      <c-icon [path]="mdiNas" slot="icon"></c-icon>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, perspiciatis?
    </c-accordion-item>
    <c-accordion-item heading="Three" value="three">
      <c-icon [path]="mdiCamera" slot="icon"></c-icon>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia voluptatum perspiciatis
      itaque!
    </c-accordion-item>
  </c-accordion>
</app-example>

// packages/csc-ui-documentation/components/examples/CAccordion.vue
<template>
  <component-example name="basic" rows>
    <template #title>Default</template>

    <c-accordion value="one">
      <c-accordion-item heading="One" value="one">
        <c-icon slot="icon" :path="mdiAccessPoint" />
        Lorem ipsum dolor sit amet.
      </c-accordion-item>

      <c-accordion-item heading="Two" value="two">
        <c-icon slot="icon" :path="mdiNas" />
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum,
        perspiciatis?
      </c-accordion-item>

      <c-accordion-item heading="Three" value="three">
        <c-icon slot="icon" :path="mdiCamera" />
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia
        voluptatum perspiciatis itaque!
      </c-accordion-item>
    </c-accordion>
  </component-example>

  <component-example name="mandatory" rows>
    <template #title>Mandatory selection</template>

    <template #subtitle>One expanded panel is required</template>

    <c-accordion value="one" mandatory>
      <c-accordion-item heading="One" value="one">
        <c-icon slot="icon" :path="mdiAccessPoint" />
        Lorem ipsum dolor sit amet.
      </c-accordion-item>

      <c-accordion-item heading="Two" value="two">
        <c-icon slot="icon" :path="mdiNas" />
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum,
        perspiciatis?
      </c-accordion-item>

      <c-accordion-item heading="Three" value="three">
        <c-icon slot="icon" :path="mdiCamera" />
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia
        voluptatum perspiciatis itaque!
      </c-accordion-item>
    </c-accordion>
  </component-example>

  <component-example name="multiple" rows>
    <template #title>Multiple</template>

    <template #subtitle>Allow multiple expanded panels</template>

    <c-accordion :value="[]" multiple>
      <c-accordion-item heading="One" value="one">
        <c-icon slot="icon" :path="mdiAccessPoint" />
        Lorem ipsum dolor sit amet.
      </c-accordion-item>

      <c-accordion-item heading="Two" value="two">
        <c-icon slot="icon" :path="mdiNas" />
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum,
        perspiciatis?
      </c-accordion-item>

      <c-accordion-item heading="Three" value="three">
        <c-icon slot="icon" :path="mdiCamera" />
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia
        voluptatum perspiciatis itaque!
      </c-accordion-item>
    </c-accordion>
  </component-example>

  <component-example name="outlined" rows>
    <template #title>Outlined items</template>

    <c-accordion value="three" outlined>
      <c-accordion-item heading="One" value="one">
        <c-icon slot="icon" :path="mdiAccessPoint" />
        Lorem ipsum dolor sit amet.
      </c-accordion-item>

      <c-accordion-item heading="Two" value="two">
        <c-icon slot="icon" :path="mdiNas" />
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum,
        perspiciatis?
      </c-accordion-item>

      <c-accordion-item heading="Three" value="three">
        <c-icon slot="icon" :path="mdiCamera" />
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia
        voluptatum perspiciatis itaque!
      </c-accordion-item>
    </c-accordion>
  </component-example>
</template>

<script setup lang="ts">
import { mdiAccessPoint, mdiCamera, mdiNas } from '@mdi/js';
</script>

<style lang="scss"></style>
