// packages/csc-ui/documentation/angular/src/app/examples/c-button/c-button.component.ts
import { Component, OnInit } from '@angular/core';
import { mdiLogin, mdiArrowRight, mdiArrowLeft } from '@mdi/js';

@Component({
  selector: 'app-c-button',
  templateUrl: './c-button.component.html',
  styleUrls: ['./c-button.component.scss'],
})
export class CButtonComponent implements OnInit {
  constructor() {}

  mdiLogin = mdiLogin;

  mdiArrowRight = mdiArrowRight;

  mdiArrowLeft = mdiArrowLeft;

  ngOnInit(): void {}
}

<app-example title="Default button" name="basic" component="c-button" cols>
  <c-button>Default</c-button>
  <c-button loading>Default</c-button>
  <c-button disabled>Default</c-button>
</app-example>

<app-example title="Outlined variant" name="outlined" component="c-button" cols>
  <c-button outlined>Outlined</c-button>
  <c-button outlined loading>Outlined</c-button>
  <c-button outlined disabled>Outlined</c-button>
</app-example>

<app-example title="Ghost variant" name="ghost" component="c-button" cols>
  <c-button ghost>Ghost</c-button>
  <c-button ghost loading>Ghost</c-button>
  <c-button ghost disabled>Ghost</c-button>
</app-example>

<app-example title="Text variant" name="text" component="c-button" cols>
  <c-button text>Text</c-button>
  <c-button text loading>Text</c-button>
  <c-button text disabled>Text</c-button>
</app-example>

<app-example title="Danger variant" name="danger" component="c-button" cols>
  <c-button danger>Danger</c-button>
  <c-button danger loading>Danger</c-button>
  <c-button danger disabled>Danger</c-button>
</app-example>

<app-example
  title="Inverted variant"
  subtitle="For dark backgrounds"
  name="inverted"
  component="c-button"
  cols
>
  <c-row gap="8" style="background-color: #006878; padding: 24px">
    <c-button inverted>Default</c-button>
    <c-button inverted disabled>Default</c-button>
    <c-button inverted outlined>Outlined</c-button>
    <c-button inverted outlined disabled>Outlined</c-button>
    <c-button inverted ghost>Ghost</c-button>
    <c-button inverted ghost disabled>Ghost</c-button>
    <c-button inverted text>Text</c-button>
    <c-button inverted text disabled>Text</c-button>
  </c-row>
</app-example>

<app-example title="No radius" name="noRadius" component="c-button" cols>
  <c-button no-radius>No radius</c-button>
  <c-button no-radius loading>No radius</c-button>
  <c-button no-radius disabled>No radius</c-button>
</app-example>

<app-example title="Fitted" name="fit" component="c-button">
  <c-button fit>Fitted</c-button>
</app-example>

<app-example title="With icon" name="icon" component="c-button" cols>
  <c-button>
    <c-icon [path]="mdiLogin" slot="icon"></c-icon>
    Login
  </c-button>
  <c-button loading>
    <c-icon [path]="mdiLogin" slot="icon"></c-icon>
    Login
  </c-button>
  <c-button disabled>
    <c-icon [path]="mdiLogin" slot="icon"></c-icon>
    Login
  </c-button>
  <c-button text icon-end>
    <c-icon [path]="mdiArrowRight" slot="icon"></c-icon>
    Next
  </c-button>
</app-example>

<app-example title="Button sizes" class="align-bottom" name="sizes" component="c-button" cols>
  <c-button size="small">Small</c-button>
  <c-button size="small" loading>Small</c-button>
  <c-button>Default</c-button>
  <c-button size="large">Large</c-button>
  <c-button size="large" loading>Large</c-button>
</app-example>

<app-example
  title="With description"
  class="align-bottom"
  name="description"
  component="c-button"
  cols
>
  <c-button>
    standard.tiny
    <div slot="description">
      <div>80 GB storage</div>
      <div>1 GB RAM | 1 CPU</div>
    </div>
  </c-button>

  <c-button outlined>
    standard.small
    <div slot="description">
      <div>80 GB storage</div>
      <div>2 GB RAM | 2 CPU</div>
    </div>
  </c-button>

  <c-button ghost>
    standard.medium
    <div slot="description">
      <div>80 GB storage</div>
      <div>4 GB RAM | 3 CPU</div>
    </div>
  </c-button>

  <c-button disabled>
    standard.tiny
    <div slot="description">
      <div>80 GB storage</div>
      <div>1 GB RAM | 1 CPU</div>
    </div>
  </c-button>

  <c-button outlined disabled>
    standard.small
    <div slot="description">
      <div>80 GB storage</div>
      <div>2 GB RAM | 2 CPU</div>
    </div>
  </c-button>

  <c-button ghost disabled>
    standard.medium
    <div slot="description">
      <div>80 GB storage</div>
      <div>4 GB RAM | 3 CPU</div>
    </div>
  </c-button>
</app-example>

<app-example
  title="Sizes and descriptions"
  class="align-bottom"
  name="sizeAndDescription"
  component="c-button"
  cols
>
  <c-button size="small">
    standard.tiny
    <div slot="description">
      <div>80 GB storage</div>
      <div>1 GB RAM | 1 CPU</div>
    </div>
  </c-button>

  <c-button size="small" loading>
    standard.tiny
    <div slot="description">
      <div>80 GB storage</div>
      <div>1 GB RAM | 1 CPU</div>
    </div>
  </c-button>

  <c-button>
    standard.small
    <div slot="description">
      <div>80 GB storage</div>
      <div>2 GB RAM | 2 CPU</div>
    </div>
  </c-button>

  <c-button loading>
    standard.small
    <div slot="description">
      <div>80 GB storage</div>
      <div>2 GB RAM | 2 CPU</div>
    </div>
  </c-button>

  <c-button size="large">
    standard.medium
    <div slot="description">
      <div>80 GB storage</div>
      <div>4 GB RAM | 3 CPU</div>
    </div>
  </c-button>
</app-example>

// packages/csc-ui-documentation/components/examples/CButton.vue
<template>
  <component-example name="variants">
    <template #title>Variants</template>

    <c-button>Default</c-button>
    <c-button outlined>Outlined</c-button>
    <c-button ghost>Ghost</c-button>
    <c-button text>Text</c-button>
    <c-button danger>Danger</c-button>
  </component-example>

  <component-example name="loading">
    <template #title>Loading state</template>

    <c-button loading>Default</c-button>
    <c-button loading outlined>Outlined</c-button>
    <c-button loading ghost>Ghost</c-button>
    <c-button loading text>Text</c-button>
    <c-button loading danger>Danger</c-button>
  </component-example>

  <component-example name="disabled">
    <template #title>Disabled state</template>

    <c-button disabled>Default</c-button>
    <c-button disabled outlined>Outlined</c-button>
    <c-button disabled ghost>Ghost</c-button>
    <c-button disabled text>Text</c-button>
    <c-button disabled danger>Danger</c-button>
  </component-example>

  <component-example name="icon">
    <template #title>With icon</template>

    <c-button>
      <c-icon slot="icon" :path="mdiLogin"></c-icon>
      Login
    </c-button>

    <c-button ghost>
      <c-icon slot="icon" :path="mdiLogout"></c-icon>
      Logout
    </c-button>

    <c-button disabled>
      <c-icon slot="icon" :path="mdiLogin"></c-icon>
      Login
    </c-button>

    <c-button text icon-end>
      <c-icon slot="icon" :path="mdiArrowRight"></c-icon>
      Next
    </c-button>

    <c-button danger>
      <c-icon slot="icon" :path="mdiDelete"></c-icon>
      Delete
    </c-button>
  </component-example>
</template>

<script setup lang="ts">
// @example-start|icon
import { mdiArrowRight, mdiDelete, mdiLogin, mdiLogout } from '@mdi/js';
// @example-end
</script>

<style lang="scss"></style>
