// packages/csc-ui/documentation/angular/src/app/examples/c-progress-bar/c-progress-bar.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';

@Component({
  selector: 'app-c-progress-bar',
  templateUrl: './c-progress-bar.component.html',
  styleUrls: ['./c-progress-bar.component.scss'],
})
export class CProgressBarComponent implements OnInit, OnDestroy {
  // @example-start|basic
  progress = 0;

  interval = null;

  ngOnInit() {
    this.interval = setInterval(() => {
      this.progress = Math.ceil(Math.random() * 100);
    }, 2000);
  }

  ngOnDestroy() {
    clearInterval(this.interval);
  }
  // @example-end
}

<app-example title="Basic usage" name="basic" component="c-progress-bar" rows>
  <c-progress-bar value="50"></c-progress-bar>
  <c-progress-bar [value]="progress"></c-progress-bar>
</app-example>

<app-example title="Custom colors" name="customColors" component="c-progress-bar" rows>
  <c-progress-bar
    value="75"
    color="var(--c-error-700)"
    aria-label="Remaining resources"
  ></c-progress-bar>
  <c-progress-bar value="37" color="#16c1dd"></c-progress-bar>
</app-example>

<app-example title="Indeterminate state" name="indeterminate" component="c-progress-bar" rows>
  <c-progress-bar indeterminate></c-progress-bar>
  <c-progress-bar indeterminate color="#16c1dd"></c-progress-bar>
</app-example>

<app-example title="Adjacent details" name="adjacent" component="c-progress-bar" rows>
  <c-progress-bar single-line value="-25"></c-progress-bar>
  <c-progress-bar single-line label="complete" value="55"></c-progress-bar>
</app-example>

// packages/csc-ui-documentation/components/examples/CProgressBar.vue
<template>
  <component-example name="basic" rows>
    <template #title>Basic usage</template>

    <c-progress-bar value="50"></c-progress-bar>
    <c-progress-bar :value="progress"></c-progress-bar>
  </component-example>

  <component-example name="indeterminate" rows>
    <template #title>Indeterminate state</template>

    <c-progress-bar indeterminate></c-progress-bar>
  </component-example>
</template>

<script setup lang="ts">
// @example-start|basic
const progress = ref(25);

const interval = setInterval(() => {
  progress.value = Math.ceil(Math.random() * 100);
}, 2000);

onBeforeUnmount(() => {
  clearInterval(interval);
});
// @example-end
</script>

<style lang="scss"></style>
