// packages/csc-ui/documentation/angular/src/app/examples/c-switch/c-switch.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-c-switch',
  templateUrl: './c-switch.component.html',
  styleUrls: ['./c-switch.component.scss'],
})
export class CSwitchComponent {
  // @example-start|usage
  switch1 = false;

  switch2 = true;
  // @example-end
}

<app-example title="Usage" name="usage" component="c-switch" rows>
  <c-switch [(ngModel)]="switch1" cControl>{{ switch1 ? 'Active' : 'Inactive' }}</c-switch>

  <c-switch [(ngModel)]="switch2" cControl>{{ switch2 ? 'Active' : 'Inactive' }}</c-switch>

  <c-switch required>Required</c-switch>

  <c-switch value="true" disabled>Disabled, active</c-switch>

  <c-switch disabled>Disabled</c-switch>
</app-example>

// packages/csc-ui-documentation/components/examples/CSwitch.vue
<template>
  <component-example name="basic" rows>
    <template #title>Basic usage</template>
    <c-switch v-model="switch1" v-control>
      {{ switch1 ? 'Active' : 'Inactive' }}
    </c-switch>

    <c-switch v-model="switch2" v-control>
      {{ switch2 ? 'Active' : 'Inactive' }}
    </c-switch>

    <c-switch required>Required</c-switch>

    <c-switch value="true" disabled>Disabled, active</c-switch>

    <c-switch disabled>Disabled</c-switch>
  </component-example>
</template>

<script setup lang="ts">
// @example-start|basic
import { ref } from 'vue';

const switch1 = ref(false);

const switch2 = ref(true);
// @example-end
</script>

<style lang="scss"></style>
