// packages/csc-ui-next/src/components/c-steps/CSteps.vue
<template>
  <span class="visuallyhidden">{{ a11yMessage }}</span>
  <div ref="stepsEl" class="c-steps flex w-full flex-nowrap" aria-hidden="true">
    <slot />
  </div>
  <div v-if="isMobile" class="c-steps__label" aria-hidden="true">
    {{ label }}
  </div>
</template>

<script setup lang="ts">
import {
  computed,
  onBeforeUnmount,
  onMounted,
  ref,
  useHost,
  useTemplateRef,
  watch,
} from "vue";

const props = defineProps({
  value: { type: [Number, String], default: 1 },
});

const host = useHost();
const stepsEl = useTemplateRef<HTMLElement>("stepsEl");
const isMobile = ref(false);
const label = ref("");
const stepCount = ref(0);

let initialized = false;

// Reflect current/complete onto each <c-step> and maintain `.divider`
// elements between them in the light DOM (projected through the slot and
// styled via ::slotted(.divider)). Faithful to the Stencil version which
// imperatively inserts divider <div>s as siblings of the steps.
const handleDividers = () => {
  if (!host) return;
  const steps = Array.from(host.querySelectorAll("c-step")) as HTMLElement[];
  const dividers = host.querySelectorAll(".divider");
  stepCount.value = steps.length;

  steps.forEach((item, index) => {
    const current = index + 1 === +props.value;
    const complete = index + 1 < +props.value;
    (item as unknown as { current: boolean }).current = current;
    (item as unknown as { complete: boolean }).complete = complete;

    if (index + 1 < steps.length) {
      const div = (
        initialized ? dividers[index] : document.createElement("div")
      ) as HTMLDivElement;
      div.classList.toggle("complete", complete);
      if (!initialized) {
        div.classList.add("divider");
        item.after(div);
      }
    }

    if (current) label.value = item.textContent || "";
  });

  initialized = true;
};

const a11yMessage = computed(() => {
  const total = stepCount.value;
  const current = +props.value;
  if (!total) return "";
  const completed = current - 1;
  return `Steps, step ${Math.min(current, total)} of ${total}. ${label.value}. ${completed} step${completed !== 1 ? "s" : ""} marked as completed.`;
});

let resizeObserver: ResizeObserver | null = null;

onMounted(() => {
  if (!host) return;
  host.setAttribute("tabindex", "0");
  handleDividers();

  resizeObserver = new ResizeObserver(([entry]) => {
    const steps = host.querySelectorAll("c-step");
    const maxWidth = steps.length * 180;
    isMobile.value = maxWidth > entry.contentRect.width;
    stepsEl.value?.classList.toggle("mobile", isMobile.value);
    steps.forEach((node) => node.classList.toggle("mobile", isMobile.value));
  });
  requestAnimationFrame(() => host && resizeObserver?.observe(host));
});

onBeforeUnmount(() => {
  resizeObserver?.disconnect();
});

watch(() => props.value, handleDividers);
</script>

<style>
:host {
  --_c-steps-outline-color: var(--c-steps-outline-color, var(--c-primary-600));
  --_c-steps-color: var(--c-step-color, var(--c-tertiary-500));
  --_c-steps-color-complete: var(--c-step-color-complete, var(--c-primary-600));

  width: 100%;
  display: grid;
  gap: 8px;
  border-radius: 6px;
}

:host(:focus) {
  outline: none;
}

:host(:focus-visible) {
  outline: 2px var(--_c-steps-outline-color) solid;
  outline-offset: 2px;
}

.c-steps {
  --c-steps-divider-width: calc(100% + 160px);
  --c-steps-divider-margin: 10px -80px 0;
}

.c-steps slot {
  display: flex;
  justify-items: space-between;
  width: 100%;
}

::slotted(.divider) {
  height: 2px;
  flex: 1;
  background-color: var(--_c-steps-color);
  width: var(--c-steps-divider-width);
  margin: var(--c-steps-divider-margin) !important;
}

::slotted(.divider.complete) {
  background-color: var(--_c-steps-color-complete);
  height: 4px;
  margin-top: 9px;
}

.c-steps.mobile {
  --c-steps-divider-width: calc(100% + 11px);
  --c-steps-divider-margin: 10px -10px 0;
}

.c-steps__label {
  text-align: center;
  font-weight: 500;
}

.visuallyhidden {
  border: 0;
  clip: rect(0 0 0 0);
  height: 1px;
  margin: -1px;
  overflow: hidden;
  padding: 0;
  position: absolute;
  white-space: nowrap;
  width: 1px;
}
</style>

// packages/csc-ui/src/components/c-steps/c-steps.tsx
import {
  Component,
  Host,
  h,
  Prop,
  EventEmitter,
  Event,
  Element,
  Watch,
  State,
} from '@stencil/core';

/**
 * @group Indicators
 * @slot Default slot - Default slot
 */
@Component({
  tag: 'c-steps',
  styleUrl: 'c-steps.scss',
  shadow: true,
})
export class CSteps {
  @Element() host: HTMLCStepsElement;

  /**
   * Value of the accordion (current step number)
   */
  @Prop() value!: number | string;

  /**
   * Emit changes to the parent
   */
  @Event({ bubbles: false })
  changeValue: EventEmitter<number | string>;

  @State() isMobile = false;

  @State() label = '';

  @Watch('value')
  watchPropHandler() {
    this._handleDividers();
  }

  private _isInitialized = false;

  private _resizeObserver: ResizeObserver;

  private _stepElements: NodeListOf<HTMLCStepElement>;

  private _handleDividers() {
    this._stepElements = this.host.querySelectorAll('c-step');
    const dividers: NodeListOf<HTMLDivElement> =
      this.host.querySelectorAll('.divider');

    this._stepElements.forEach((item, index) => {
      item.current = index + 1 === +this.value;
      item.complete = index + 1 < +this.value;

      if (index + 1 < this._stepElements.length) {
        const div = this._isInitialized
          ? dividers[index]
          : document.createElement('div');

        div.classList.toggle('complete', !!item.complete);

        if (!this._isInitialized) {
          div.classList.add('divider');

          item.after(div);
        }
      }

      if (item.current) {
        this.label = item.textContent;
      }
    });

    this._isInitialized = true;
  }

  componentDidLoad() {
    this._handleDividers();

    this._resizeObserver = new ResizeObserver(([entry]) => {
      const maxWidth = this._stepElements.length * 180;

      this.isMobile = maxWidth > entry.contentRect.width;

      this.host.shadowRoot
        .querySelector('.c-steps')
        .classList.toggle('mobile', this.isMobile);

      this._stepElements.forEach((node) => {
        node.classList.toggle('mobile', this.isMobile);
      });
    });

    window.requestAnimationFrame(() => {
      this._resizeObserver.observe(this.host);
    });
  }

  private _getA11yMessage(total: number, current: number) {
    return `
      Steps, step ${Math.min(current, total)} of ${total}.
      ${this.label}.
      ${current - 1} step${current - 1 !== 1 ? 's' : ''} marked as completed.
    `;
  }

  render() {
    return (
      <Host tabindex="0">
        {this._stepElements && (
          <span class="visuallyhidden">
            {this._getA11yMessage(this._stepElements.length, +this.value)}
          </span>
        )}
        <div class="c-steps" aria-hidden="true">
          <slot></slot>
        </div>
        {this.isMobile && (
          <div class="c-steps__label" aria-hidden="true">
            {this.label}
          </div>
        )}
      </Host>
    );
  }
}
