// packages/csc-ui/src/components/c-row/c-row.tsx
import { Component, Element, h, Host, Prop } from '@stencil/core';

/**
 * Generic flex row component
 *
 * @group Layout
 * @slot Default slot - Should contain items to be displayed in the row
 */
@Component({
  tag: 'c-row',
  styleUrl: 'c-row.scss',
  shadow: true,
})
export class CRow {
  @Element() el: HTMLCRowElement;

  /**
   * Gap between items in px
   */
  @Prop() gap = 0;

  /**
   * Disable flex wrap
   */
  @Prop() nowrap = false;

  /**
   * Align items vertically
   */
  @Prop() align: 'start' | 'center' | 'end';

  /**
   * Justify content horizontally
   */
  @Prop() justify:
    | 'start'
    | 'center'
    | 'end'
    | 'space-between'
    | 'space-around';

  componentDidLoad() {
    this.el.style.setProperty('--_c-row-gap', this.el.dataset.gap);
  }

  render() {
    const classes = {
      'c-row': true,
      'c-row--nowrap': this.nowrap,
      [`c-row--align-${this.align}`]: !!this.align,
      [`c-row--justify-${this.justify}`]: !!this.justify,
    };

    return (
      <Host data-gap={`${this.gap}px`} class={classes}>
        <slot></slot>
      </Host>
    );
  }
}

// packages/csc-ui-next/src/components/c-row/CRow.vue
<template>
  <slot />
</template>

<script setup lang="ts">
import { onMounted, useHost, watchEffect } from 'vue';

const props = defineProps({
  gap: { type: Number, default: 0 },
  nowrap: { type: Boolean, default: false },
  align: { type: String, default: '' },
  justify: { type: String, default: '' },
});

// `--_c-row-gap` is read from the host's inline style by every gap rule.
// Stencil sets it once in componentDidLoad; mirror that with watchEffect
// so dynamic prop changes still update the gap.
const host = useHost();
onMounted(() => {
  if (!host) return;
  watchEffect(() => {
    host.style.setProperty('--_c-row-gap', `${props.gap}px`);
  });
});
</script>

<style>
:host {
  --_c-row-gap: 0px;

  display: flex;
  flex: 1 1 auto;
  flex-wrap: wrap;
  gap: var(--_c-row-gap);
}

:host([nowrap]) {
  flex-wrap: nowrap !important;
}

:host([align='center']) { align-items: center; }
:host([align='start']) { align-items: flex-start; }
:host([align='end']) { align-items: flex-end; }

:host([justify='start']) { justify-content: flex-start; }
:host([justify='center']) { justify-content: center; }
:host([justify='end']) { justify-content: flex-end; }
:host([justify='space-between']) { justify-content: space-between; }
:host([justify='space-around']) { justify-content: space-around; }
</style>
