// packages/csc-ui-documentation/app/examples/c-number-field/step.react.tsx
// @ts-nocheck — documentation code sample; shown as text, never compiled here
import { useState } from 'react';
import { CNumberField } from '@cscfi/csc-ui-react';

export const Step = () => {
  const [volume, setVolume] = useState<number | null>(50);

  return (
    <div>
      <CNumberField
        value={volume}
        max={100}
        min={0}
        step={5}
        hint="0 to 100, in steps of 5"
        label="Volume"
        onChange={(event) => setVolume(event.detail as number | null)}
      >
        <span slot="post">%</span>
      </CNumberField>

      <p>Value: {volume ?? 'null'}</p>
    </div>
  );
};

// packages/csc-ui-documentation/app/examples/c-number-field/step.vue
<template>
  <div>
    <c-number-field
      v-model="volume"
      :max="100"
      :min="0"
      :step="5"
      hint="0 to 100, in steps of 5"
      label="Volume"
    >
      <span slot="post">%</span>
    </c-number-field>

    <p>Value: {{ volume ?? 'null' }}</p>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const volume = ref<null | number>(50);
</script>
