// packages/csc-ui-documentation/app/examples/c-date-picker/lazy-month.react.tsx
// @ts-nocheck — documentation code sample; shown as text, never compiled here
import { useState } from 'react';
import { CDatePicker } from '@cscfi/csc-ui-react';

// A simulated booking API: the fully booked days of one month.
const fetchBooked = (month: string): Promise<string[]> =>
  new Promise((resolve) =>
    setTimeout(
      () =>
        resolve(
          ['03', '04', '11', '17', '18', '25'].map((d) => `${month}-${d}`),
        ),
      300,
    ),
  );

export const LazyMonth = () => {
  const [date, setDate] = useState<string | null>(null);
  const [booked, setBooked] = useState<string[]>([]);

  return (
    <div>
      {/* `change:month` names the displayed month — on open too — so the
          booked days load one month at a time. */}
      <CDatePicker
        value={date}
        disabledDates={booked}
        hint="Booked days load as you browse"
        label="Booking"
        onChange={(event) => setDate(event.detail as string | null)}
        onChangeMonth={async (event) =>
          setBooked(await fetchBooked(event.detail as string))
        }
      />

      <p>Value: {date ?? 'null'}</p>
    </div>
  );
};

// packages/csc-ui-documentation/app/examples/c-date-picker/lazy-month.vue
<template>
  <div>
    <!-- `change:month` names the displayed month — on open too — so the
         booked days load one month at a time. -->
    <c-date-picker
      v-model="date"
      :disabled-dates="booked"
      hint="Booked days load as you browse"
      label="Booking"
      @change:month="onMonth"
    />

    <p>Value: {{ date ?? 'null' }}</p>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

// A simulated booking API: the fully booked days of one month.
const fetchBooked = (month: string): Promise<string[]> =>
  new Promise((resolve) =>
    setTimeout(
      () =>
        resolve(
          ['03', '04', '11', '17', '18', '25'].map((d) => `${month}-${d}`),
        ),
      300,
    ),
  );

const booked = ref<string[]>([]);

const date = ref<null | string>(null);

const onMonth = async (event: CustomEvent<string>) => {
  booked.value = await fetchBooked(event.detail);
};
</script>
