// packages/csc-ui-documentation/app/examples/c-date-picker/month.react.tsx
import type { CDatePickerRange } from '@cscfi/csc-ui';

import { CDatePicker } from '@cscfi/csc-ui-react';
// @ts-nocheck — documentation code sample; shown as text, never compiled here
import { useState } from 'react';

export const Month = () => {
  const [billing, setBilling] = useState<null | string>(null);

  const [period, setPeriod] = useState<CDatePickerRange | null>(null);

  return (
    <div>
      <CDatePicker
        clearable
        hint="Type a month or open the month list"
        label="Billing month"
        onChange={(event) => setBilling(event.detail as null | string)}
        type="month"
        value={billing}
      />

      <p>Value: {billing ?? 'null'}</p>

      <CDatePicker
        clearable
        label="Reporting period"
        onChange={(event) => setPeriod(event.detail as CDatePickerRange | null)}
        range
        type="month"
        value={period}
      />

      <p>Value: {period ? `${period.start} – ${period.end}` : 'null'}</p>
    </div>
  );
};

// packages/csc-ui-documentation/app/examples/c-date-picker/month.vue
<template>
  <div>
    <c-date-picker
      v-model="billing"
      hint="Type a month or open the month list"
      label="Billing month"
      type="month"
      clearable
    />

    <p>Value: {{ billing ?? 'null' }}</p>

    <c-date-picker
      v-model="period"
      label="Reporting period"
      type="month"
      range
      clearable
    />

    <p>Value: {{ period ? `${period.start} – ${period.end}` : 'null' }}</p>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

import type { CDatePickerRange } from '@cscfi/csc-ui';

const billing = ref<string | null>(null);

const period = ref<CDatePickerRange | null>(null);
</script>
