// packages/csc-ui-documentation-next/app/examples/c-pagination/simple.vue
<template>
  <div>
    <c-pagination
      :value.prop="options"
      hide-details
      simple
      @change-value="onChange"
    />

    <p>Current page: {{ page }}</p>
  </div>
</template>

<script setup lang="ts">
import type { CPaginationOptions } from '@cscfi/csc-ui-next';

const options = ref<CPaginationOptions>({
  itemCount: 40,
  itemsPerPage: 10,
});

const page = ref(1);

const onChange = (event: Event) => {
  page.value =
    (event as CustomEvent<CPaginationOptions>).detail.currentPage ?? 1;
};
</script>

// packages/csc-ui-documentation-next/app/examples/c-pagination/simple.react.tsx
// @ts-nocheck — documentation code sample; shown as text, never compiled here
import { useState } from 'react';
import { CPagination } from '@cscfi/csc-ui-next-react';
import type { CPaginationOptions } from '@cscfi/csc-ui-next';

export const Simple = () => {
  const [options] = useState<CPaginationOptions>({
    itemCount: 40,
    itemsPerPage: 10,
  });

  const [page, setPage] = useState(1);

  return (
    <div>
      <CPagination
        value={options}
        hideDetails
        simple
        onChangeValue={(event) =>
          setPage((event.detail as CPaginationOptions).currentPage ?? 1)
        }
      />

      <p>Current page: {page}</p>
    </div>
  );
};
