// packages/csc-ui-documentation/app/examples/c-tabs/vertical.react.tsx
// @ts-nocheck — documentation code sample; shown as text, never compiled here
import { CTab, CTabItem, CTabItems, CTabs } from '@cscfi/csc-ui-react';

export const Vertical = () => (
  <div>
    <CTabs value="profile" vertical>
      <CTab value="profile">Profile</CTab>
      <CTab value="security">Security</CTab>
      <CTab value="tokens">API tokens</CTab>

      <CTabItems slot="items">
        <CTabItem value="profile">
          <p>Your name, email and avatar.</p>
        </CTabItem>
        <CTabItem value="security">
          <p>Password and two-factor authentication.</p>
        </CTabItem>
        <CTabItem value="tokens">
          <p>Personal access tokens for the API.</p>
        </CTabItem>
      </CTabItems>
    </CTabs>
  </div>
);

// packages/csc-ui-documentation/app/examples/c-tabs/vertical.vue
<template>
  <div>
    <c-tabs value="profile" vertical>
      <c-tab value="profile">Profile</c-tab>

      <c-tab value="security">Security</c-tab>

      <c-tab value="tokens">API tokens</c-tab>

      <c-tab-items slot="items">
        <c-tab-item value="profile">
          <p>Your name, email and avatar.</p>
        </c-tab-item>

        <c-tab-item value="security">
          <p>Password and two-factor authentication.</p>
        </c-tab-item>

        <c-tab-item value="tokens">
          <p>Personal access tokens for the API.</p>
        </c-tab-item>
      </c-tab-items>
    </c-tabs>
  </div>
</template>
