// packages/csc-ui-documentation/app/examples/c-pagination/simple.vue
<template>
  <div>
    <c-pagination v-model="options" hide-details simple />

    <p>Current page: {{ options.currentPage ?? 1 }}</p>
  </div>
</template>

<script setup lang="ts">
import type { CPaginationOptions } from '@cscfi/csc-ui';

import { ref } from 'vue';

const options = ref<CPaginationOptions>({
  itemCount: 40,
  itemsPerPage: 10,
});
</script>

// packages/csc-ui-documentation/app/examples/c-pagination/simple.react.tsx
import type { CPaginationOptions } from '@cscfi/csc-ui';

import { CPagination } from '@cscfi/csc-ui-react';
// @ts-nocheck — documentation code sample; shown as text, never compiled here
import { useState } from 'react';

export const Simple = () => {
  const [options] = useState<CPaginationOptions>({
    itemCount: 40,
    itemsPerPage: 10,
  });

  const [page, setPage] = useState(1);

  return (
    <div>
      <CPagination
        hideDetails
        onChangeValue={(event) =>
          setPage((event.detail as CPaginationOptions).currentPage ?? 1)
        }
        simple
        value={options}
      />

      <p>Current page: {page}</p>
    </div>
  );
};
