// packages/csc-ui-documentation/app/examples/c-radio-group/custom-layout.react.tsx
import { CRadio, CRadioGroup } from '@cscfi/csc-ui-react';
// @ts-nocheck — documentation code sample; shown as text, never compiled here
import { useState } from 'react';

const styles = `
/* The radios are ordinary light DOM: wrap them in your own layout markup and
   style it with your own CSS. Keep the label text inside the <c-radio> so the
   whole row stays click-associated. */
.plan-option {
  border: 1px solid var(--c-border);
  border-radius: 0.5rem;
  padding: 0 0.75rem;
}
`;

export const CustomLayout = () => {
  const [plan, setPlan] = useState('free');

  return (
    <>
      <style>{styles}</style>

      <CRadioGroup
        hint="You can change the plan later"
        label="Subscription plan"
        onChangeValue={(event) => setPlan(event.detail as string)}
        value={plan}
      >
        <div className="plan-option">
          <CRadio value="free">Free</CRadio>
        </div>
        <div className="plan-option">
          <CRadio value="pro">Pro</CRadio>
        </div>
        <div className="plan-option">
          <CRadio value="enterprise">Enterprise</CRadio>
        </div>
      </CRadioGroup>
    </>
  );
};

// packages/csc-ui-documentation/app/examples/c-radio-group/custom-layout.vue
<template>
  <div>
    <c-radio-group
      v-model="plan"
      hint="You can change the plan later"
      label="Subscription plan"
    >
      <div class="plan-option">
        <c-radio value="free">Free</c-radio>
      </div>

      <div class="plan-option">
        <c-radio value="pro">Pro</c-radio>
      </div>

      <div class="plan-option">
        <c-radio value="enterprise">Enterprise</c-radio>
      </div>
    </c-radio-group>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const plan = ref<'enterprise' | 'free' | 'pro'>('free');
</script>

<style>
/* The radios are ordinary light DOM: wrap them in your own layout markup and
   style it with your own CSS. Keep the label text inside the <c-radio> so the
   whole row stays click-associated. */
.plan-option {
  border: 1px solid var(--c-border);
  border-radius: 0.5rem;
  padding: 0 0.75rem;
}
</style>
