// packages/csc-ui-documentation/app/examples/c-radio-group/inline.vue
<template>
  <div>
    <c-radio-group
      v-model="frequency"
      hide-details
      inline
      label="Email frequency"
    >
      <c-radio value="daily">Daily</c-radio>

      <c-radio value="weekly">Weekly</c-radio>

      <c-radio value="never">Never</c-radio>
    </c-radio-group>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const frequency = ref('weekly');
</script>

// packages/csc-ui-documentation/app/examples/c-radio-group/inline.react.tsx
// @ts-nocheck — documentation code sample; shown as text, never compiled here
import { useState } from 'react';
import { CRadio, CRadioGroup } from '@cscfi/csc-ui-react';

export const Inline = () => {
  const [frequency, setFrequency] = useState('weekly');

  return (
    <div>
      <CRadioGroup
        value={frequency}
        hideDetails
        inline
        label="Email frequency"
        onChangeValue={(event) => setFrequency(event.detail as string)}
      >
        <CRadio value="daily">Daily</CRadio>
        <CRadio value="weekly">Weekly</CRadio>
        <CRadio value="never">Never</CRadio>
      </CRadioGroup>
    </div>
  );
};
