// packages/csc-ui-documentation/app/examples/c-menu-item/active-items.vue
<template>
  <div class="example-row">
    <c-menu @select="onTheme">
      <c-button slot="trigger" text>
        <c-icon :path="mdiThemeLightDark" />
        Theme: {{ theme }}
        <c-icon :path="mdiChevronDown" />
      </c-button>

      <c-menu-label>Theme</c-menu-label>

      <c-menu-item
        :active="theme === 'dark'"
        :icon="mdiWeatherNight"
        value="dark"
      >
        Dark
      </c-menu-item>

      <c-menu-item
        :active="theme === 'light'"
        :icon="mdiWeatherSunny"
        value="light"
      >
        Light
      </c-menu-item>

      <c-menu-item
        :active="theme === 'system'"
        :icon="mdiMonitor"
        value="system"
      >
        System
      </c-menu-item>
    </c-menu>

    <c-menu @select="onSort">
      <c-button slot="trigger" text>
        Sort by: {{ sortBy }}
        <c-icon :path="mdiChevronDown" />
      </c-button>

      <c-menu-item
        v-for="key in sortKeys"
        :key="key"
        :active="sortBy === key"
        :active-icon="mdiRadioboxMarked"
        :value="key"
      >
        {{ key }}
      </c-menu-item>
    </c-menu>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

import {
  mdiChevronDown,
  mdiMonitor,
  mdiRadioboxMarked,
  mdiThemeLightDark,
  mdiWeatherNight,
  mdiWeatherSunny,
} from '@mdi/js';

const theme = ref('dark');

const sortKeys = ['name', 'size', 'date'];

const sortBy = ref('name');

const onTheme = (event: Event) => {
  theme.value = (event as CustomEvent<{ value: string }>).detail.value;
};

const onSort = (event: Event) => {
  sortBy.value = (event as CustomEvent<{ value: string }>).detail.value;
};
</script>

// packages/csc-ui-documentation/app/examples/c-menu-item/active-items.react.tsx
// @ts-nocheck — documentation code sample; shown as text, never compiled here
import { useState } from 'react';
import {
  mdiChevronDown,
  mdiMonitor,
  mdiRadioboxMarked,
  mdiThemeLightDark,
  mdiWeatherNight,
  mdiWeatherSunny,
} from '@mdi/js';
import {
  CButton,
  CIcon,
  CMenu,
  CMenuItem,
  CMenuLabel,
} from '@cscfi/csc-ui-react';

export const ActiveItems = () => {
  const [theme, setTheme] = useState('dark');
  const [sortBy, setSortBy] = useState('name');

  return (
    <div className="example-row">
      <CMenu onSelect={(event) => setTheme(event.detail.value)}>
        <CButton slot="trigger" text>
          <CIcon path={mdiThemeLightDark} />
          Theme: {theme}
          <CIcon path={mdiChevronDown} />
        </CButton>

        <CMenuLabel>Theme</CMenuLabel>

        <CMenuItem
          active={theme === 'dark'}
          icon={mdiWeatherNight}
          value="dark"
        >
          Dark
        </CMenuItem>
        <CMenuItem
          active={theme === 'light'}
          icon={mdiWeatherSunny}
          value="light"
        >
          Light
        </CMenuItem>
        <CMenuItem active={theme === 'system'} icon={mdiMonitor} value="system">
          System
        </CMenuItem>
      </CMenu>

      <CMenu onSelect={(event) => setSortBy(event.detail.value)}>
        <CButton slot="trigger" text>
          Sort by: {sortBy}
          <CIcon path={mdiChevronDown} />
        </CButton>

        {['name', 'size', 'date'].map((key) => (
          <CMenuItem
            key={key}
            active={sortBy === key}
            activeIcon={mdiRadioboxMarked}
            value={key}
          >
            {key}
          </CMenuItem>
        ))}
      </CMenu>
    </div>
  );
};
