// packages/csc-ui-documentation/components/examples/CSelect.vue
<template>
  <component-example name="basic" rows>
    <template #title>Basic usage with c-option elements</template>

    <c-select
      v-model="selectedItem"
      v-control
      label="Partition"
      placeholder="Choose partition..."
      style="max-width: 360px"
      hide-details
      return-value
    >
      <c-option value="normal" name="normal">
        <c-row align="center" justify="space-between">
          Normal
          <c-tag flat>100 BU / node / h</c-tag>
        </c-row>
      </c-option>

      <c-option value="interactive" name="interactive">
        <c-row align="center" justify="space-between">
          Interactive
          <c-tag flat>1 BU / CPU / h</c-tag>
        </c-row>
      </c-option>

      <c-option value="gpu" name="gpu" disabled>
        <c-row align="center" justify="space-between">
          GPU
          <c-tag flat badge="N/A" active>100 BU / GPU / h</c-tag>
        </c-row>
      </c-option>
    </c-select>

    <p class="mt-3">Selected partition value: {{ selectedItem || '?' }}</p>
  </component-example>

  <component-example name="optionAsValue" rows>
    <template #title>Basic usage</template>

    <template #subtitle>Option as selection</template>

    <c-select
      v-model="selectedOption"
      v-control
      label="Partition"
      placeholder="Choose partition..."
      style="max-width: 360px"
      hide-details
      return-value
      option-as-selection
    >
      <c-option value="normal" name="normal">
        <c-row align="center" justify="space-between">
          Normal
          <c-tag flat>100 BU / node / h</c-tag>
        </c-row>
      </c-option>

      <c-option value="interactive" name="interactive">
        <c-row align="center" justify="space-between">
          Interactive
          <c-tag flat>1 BU / CPU / h</c-tag>
        </c-row>
      </c-option>

      <c-option value="gpu" name="gpu" disabled>
        <c-row align="center" justify="space-between">
          GPU
          <c-tag flat badge="N/A" active>100 BU / GPU / h</c-tag>
        </c-row>
      </c-option>
    </c-select>

    <p class="mt-3">Selected partition value: {{ selectedOption || '?' }}</p>
  </component-example>

  <component-example name="objectItems" rows>
    <template #title>Items as array</template>

    <c-select
      v-model="value"
      v-control
      label="Country"
      return-value
      :items="items"
      placeholder="Choose country..."
    />

    <p class="mt-3">Selected country: {{ value || 'None' }}</p>
  </component-example>
</template>

<script setup lang="ts">
// @example-start|basic|objectItems|optionAsValue
import { ref } from 'vue';
// @example-end

// @example-start|basic
const selectedItem = ref('normal');
// @example-end

// @example-start|optionAsValue
const selectedOption = ref('');
// @example-end

// @example-start|objectItems
const value = ref(null);

const items = [
  { name: 'Finland', value: 'finland' },
  { name: 'Sweden', value: 'sweden' },
  { name: 'Norway', value: 'norway' },
  { name: 'Denmark', value: 'denmark' },
  { name: 'Germany', value: 'germany' },
  { name: 'Belgium', value: 'belgium' },
  { name: 'France', value: 'france' },
];
// @example-end
</script>

<style lang="scss"></style>

// packages/csc-ui/documentation/angular/src/app/examples/c-select/c-select.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-c-select',
  templateUrl: './c-select.component.html',
  styleUrls: ['./c-select.component.scss'],
})
export class CSelectComponent implements OnInit {
  // @example-start|basic
  value = null;
  // @example-end

  // @example-start|withOptions
  selectedItem = '';
  // @example-end

  // @example-start|withOptionsRich
  selectedOption = '';
  // @example-end

  // @example-start|optionsAndSelection
  selected = '';
  // @example-end

  // @example-start|scrollable|shadow
  selection = null;
  // @example-end

  // @example-start|scrollable|basic|shadow
  items = [
    { name: 'Normal', value: 'normal' },
    { name: 'Interactive', value: 'interactive' },
    { name: 'GPU', value: 'gpu' },
  ];
  // @example-end

  constructor() {}

  ngOnInit(): void {}
}

<app-example title="Usage with c-options" name="withOptions" component="c-select">
  <c-select
    cControl
    label="Partition"
    [(ngModel)]="selectedItem"
    placeholder="Choose partition..."
    style="max-width: 360px"
    return-value
  >
    <c-option value="normal" name="normal">
      <c-row align="center" justify="space-between">
        Normal
        <c-tag flat>100 BU / node / h</c-tag>
      </c-row>
    </c-option>

    <c-option value="interactive" name="interactive">
      <c-row align="center" justify="space-between">
        Interactive
        <c-tag flat>1 BU / CPU / h</c-tag>
      </c-row>
    </c-option>

    <c-option value="gpu" name="gpu" disabled>
      <c-row align="center" justify="space-between">
        GPU
        <c-tag flat badge="N/A" active>100 BU / GPU / h</c-tag>
      </c-row>
    </c-option>
  </c-select>

  <p class="mt-3">Selected partition value: {{ selectedItem || '?' }}</p>
</app-example>

<app-example
  title="Usage with c-options"
  subtitle="Displaying the option as selection"
  name="withOptionsRich"
  component="c-select"
>
  <c-select
    cControl
    label="Partition"
    [(ngModel)]="selectedOption"
    placeholder="Choose partition..."
    style="max-width: 360px"
    option-as-selection
    return-value
  >
    <c-option value="normal" name="normal">
      <c-row align="center" justify="space-between">
        Normal
        <c-tag flat>100 BU / node / h</c-tag>
      </c-row>
    </c-option>

    <c-option value="interactive" name="interactive">
      <c-row align="center" justify="space-between">
        Interactive
        <c-tag flat>1 BU / CPU / h</c-tag>
      </c-row>
    </c-option>

    <c-option value="gpu" name="gpu">
      <c-row align="center" justify="space-between">
        GPU
        <c-tag flat>100 BU / GPU / h</c-tag>
      </c-row>
    </c-option>
  </c-select>

  <p class="mt-3">Selected partition: {{ selectedOption || '?' }}</p>
</app-example>

<app-example
  title="Usage with c-options"
  subtitle="Selected by default"
  name="optionsAndSelection"
  component="c-select"
>
  <c-select
    cControl
    label="Partition"
    [(ngModel)]="selected"
    placeholder="Choose partition..."
    return-value
  >
    <c-option value="Normal">Normal</c-option>

    <c-option value="Interactive" selected>Interactive</c-option>

    <c-option value="GPU">GPU</c-option>
  </c-select>

  <p class="mt-3">Selected partition: {{ selected || 'None' }}</p>
</app-example>

<app-example title="Basic usage with return-value (Angular)" name="basic" component="c-select">
  <c-select
    cControl
    label="Partition"
    return-value
    [items]="items"
    [(ngModel)]="value"
    placeholder="Choose partition..."
  ></c-select>

  <p class="mt-3">Selected partition: {{ value || 'None' }}</p>
</app-example>

<app-example title="Shadow variant (Angular)" name="shadow" component="c-select">
  <c-select
    shadow
    cControl
    [items]="items"
    [(ngModel)]="selection"
    placeholder="Partition"
  ></c-select>

  <p class="mt-3">Selected partition: {{ (selection | json) || 'None' }}</p>
</app-example>

<app-example title="Scrollable items + required (Angular)" name="scrollable" component="c-select">
  <c-select
    required
    cControl
    [itemsPerPage]="4"
    [items]="items"
    [(ngModel)]="selection"
    [valid]="!!selection?.value"
    label="Partition"
    placeholder="Choose partition..."
    required
  ></c-select>

  <p class="mt-3">Selected partition: {{ (selection | json) || 'None' }}</p>
</app-example>
