// packages/csc-ui-documentation/app/examples/c-time-picker/now.react.tsx
// @ts-nocheck — documentation code sample; shown as text, never compiled here
import { useState } from 'react';
import { CTimePicker } from '@cscfi/csc-ui-react';

export const Now = () => {
  const [time, setTime] = useState<string | null>('08:00');

  return (
    <div>
      <CTimePicker
        value={time}
        hint="Now under the columns commits the current minute"
        label="Arrival"
        minuteStep={15}
        showNow
        onChange={(event) => setTime(event.detail as string | null)}
      />

      <p>Value: {time ?? 'null'}</p>
    </div>
  );
};

// packages/csc-ui-documentation/app/examples/c-time-picker/now.vue
<template>
  <div>
    <c-time-picker
      v-model="time"
      :minute-step="15"
      hint="Now under the columns commits the current minute"
      label="Arrival"
      show-now
    />

    <p>Value: {{ time ?? 'null' }}</p>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const time = ref<null | string>('08:00');
</script>
