// packages/csc-ui-next/src/components/c-pagination/CPagination.vue
<template>
  <nav role="navigation" aria-label="pagination">
    <div v-if="!hideDetails" class="c-pagination__details">
      <div class="c-pagination__items-per-page">
        {{ itemsPerPageText }}
        <c-menu :items="pageSizeItems" @click="onMenuClick">
          <div><span class="items-per-page">{{ itemsPerPage }}</span></div>
        </c-menu>
      </div>
      <span :class="{ range: !simple }">{{ rangeText }}</span>
    </div>

    <ul v-if="value.itemCount">
      <li>
        <c-icon-button
          :aria-label="prevPageText"
          :disabled="(value.currentPage ?? 1) <= 1"
          :size="buttonSize"
          text
          @click="decreasePage"
        >
          <span class="visuallyhidden">{{ prevPageText }}</span>
          <c-icon :path="chevronLeft" />
        </c-icon-button>
      </li>

      <template v-if="!simple">
        <li v-for="(btn, i) in pageButtons" :key="i">
          <c-icon-button
            v-if="btn.type === 'separator'"
            aria-disabled="true"
            :size="buttonSize"
            tabindex="-1"
            role="separator"
            disabled
            text
          >
            <svg width="16" height="16" viewBox="0 0 24 24">
              <path :d="dotsIcon" fill="currentColor" />
            </svg>
          </c-icon-button>
          <c-icon-button
            v-else
            :text="currentPage !== btn.number"
            :size="buttonSize"
            :aria-current="currentPage === btn.number ? 'page' : undefined"
            @click="setPage(btn.number!)"
          >
            <span :aria-label="`page ${btn.number} of ${totalPages}`">{{ btn.number }}</span>
          </c-icon-button>
        </li>
      </template>

      <li>
        <c-icon-button
          :aria-label="nextPageText"
          :disabled="(value.currentPage ?? 1) >= totalPages"
          :size="buttonSize"
          text
          @click="increasePage"
        >
          <span class="visuallyhidden">{{ nextPageText }}</span>
          <c-icon :path="chevronRight" />
        </c-icon-button>
      </li>
    </ul>
  </nav>
</template>

<script setup lang="ts">
import { mdiChevronLeft, mdiChevronRight, mdiDotsHorizontal } from '@mdi/js';
import { computed, onMounted, ref, useHost, watch, watchEffect } from 'vue';

interface PaginationOptions {
  itemCount: number;
  currentPage?: number;
  totalVisible?: number;
  itemsPerPage?: number;
  startFrom?: number;
  endTo?: number;
  pageSizes?: number[];
  textOverrides?: Record<string, unknown>;
}

const props = defineProps({
  value: { type: Object as () => PaginationOptions, default: () => ({ itemCount: 0 }) },
  hideDetails: { type: Boolean, default: false },
  simple: { type: Boolean, default: false },
  size: { type: String, default: 'default' },
  hideRange: { type: Boolean, default: false },
});

const chevronLeft = mdiChevronLeft;
const chevronRight = mdiChevronRight;
const dotsIcon = mdiDotsHorizontal;

const host = useHost();
const dispatchValue = (value: unknown) => {
  host?.dispatchEvent(new CustomEvent('changeValue', { detail: value }));
  host?.dispatchEvent(new CustomEvent('update:value', { detail: value }));
};

const currentPage = ref(1);
const itemsPerPage = ref(25);
const totalVisible = ref(7);
const pageSizes = ref<number[]>([5, 25, 50, 100]);

const itemsPerPageText = 'Items per page:';
const prevPageText = 'Previous page';
const nextPageText = 'Next page';

const totalPages = computed(() =>
  Math.ceil(props.value.itemCount / itemsPerPage.value),
);

const buttonSize = computed(() =>
  props.size === 'small' ? 'x-small' : 'small',
);

// Recompute the visible window + write startFrom/endTo back onto the
// value object, then notify the consumer — mirrors Stencil's _setRange.
const setRange = () => {
  if (!props.value) return;
  currentPage.value = props.value.currentPage || 1;
  itemsPerPage.value = props.value.itemsPerPage || 25;
  totalVisible.value = props.value.totalVisible || 7;
  pageSizes.value = props.value.pageSizes || [5, 25, 50, 100];
  props.value.startFrom =
    currentPage.value * itemsPerPage.value - itemsPerPage.value;
  props.value.endTo = currentPage.value * itemsPerPage.value - 1;
  dispatchValue(props.value);
};

const commit = () => {
  props.value.currentPage = currentPage.value;
  props.value.itemsPerPage = itemsPerPage.value;
  setRange();
};

const setPage = (n: number) => {
  currentPage.value = n;
  commit();
};
const increasePage = () => {
  if (currentPage.value < totalPages.value) {
    currentPage.value += 1;
    commit();
  }
};
const decreasePage = () => {
  if (currentPage.value > 1) {
    currentPage.value -= 1;
    commit();
  }
};

const pageSizeItems = computed(() =>
  pageSizes.value.map((i) => ({
    name: i.toString(),
    action: () => {
      itemsPerPage.value = i;
      currentPage.value = 1;
      commit();
    },
  })),
);

const onMenuClick = (event: Event) => event.stopPropagation();

const rangeText = computed(() => {
  if (props.hideRange || !props.value.itemCount) return '';
  const end = Math.min(
    currentPage.value * itemsPerPage.value,
    props.value.itemCount,
  );
  const start = (props.value.startFrom ?? 0) + 1;
  return `${start} - ${end} of ${props.value.itemCount} items`;
});

// Build the page-button window (with leading/trailing separators) the
// same way the Stencil component does.
interface Btn {
  type: 'page' | 'separator';
  number?: number;
}
const pageButtons = computed<Btn[]>(() => {
  const total = totalPages.value;
  const visible = totalVisible.value;
  const buttons: Btn[] = [];
  let buttonStart = 0;
  let buttonCount = total + 1;
  const more = total > visible;

  if (more) {
    if (currentPage.value < visible - 2) {
      buttonCount = visible - 1;
    } else if (currentPage.value < total - visible + 4) {
      buttonStart = Math.ceil(currentPage.value - visible / 2) + 1;
      buttonCount = visible - 3;
    } else {
      buttonStart = total - visible + 2;
      buttonCount = visible - 2;
    }
  }

  if (buttonStart > 1) {
    buttons.push({ type: 'page', number: 1 });
    buttons.push({ type: 'separator' });
  }
  for (let index = 1; index < buttonCount; index++) {
    buttons.push({ type: 'page', number: buttonStart + index });
  }
  const allVisible = total <= visible;
  if (
    (currentPage.value < visible - 1 ||
      currentPage.value < total - visible + 4) &&
    !allVisible
  ) {
    buttons.push({ type: 'separator' });
  }
  if (more) buttons.push({ type: 'page', number: total });

  return buttons;
});

watch(
  () => props.value,
  (v, old) => {
    if (JSON.stringify(v) === JSON.stringify(old)) return;
    requestAnimationFrame(setRange);
  },
);

onMounted(() => {
  setRange();
  watchEffect(() => {
    if (!host) return;
    host.classList.add('c-pagination');
    host.classList.toggle('c-pagination--small', props.size === 'small');
    host.classList.toggle('c-pagination--simple', props.simple);
  });
});
</script>

<style>
:host {
  --_c-pagination-button-active-background-color: var(--c-pagination-button-active-background-color, var(--c-primary-600));
  --_c-pagination-button-active-background-color-hover: var(--c-pagination-button-active-background-color-hover, var(--c-primary-400));
  --_c-pagination-button-active-text-color: var(--c-pagination-button-active-text-color, var(--c-white));
  --_c-pagination-button-background-color: var(--c-pagination-button-background-color, var(--c-transparent));
  --_c-pagination-button-background-color-hover: var(--c-pagination-button-background-color-hover, rgba(var(--c-primary-rgb), 0.1));
  --_c-pagination-button-text-color: var(--c-pagination-button-text-color, var(--_c-pagination-button-active-background-color));
  --_c-pagination-text-color: var(--c-pagination-text-color, var(--c-text-system));
  --_c-pagination-menu-text-color: var(--c-pagination-menu-text-color, var(--c-text-system));
  --_c-pagination-menu-text-color-active: var(--c-pagination-menu-text-color-active, var(--c-primary-600));
  --_c-pagination-menu-background-color-hover: var(--c-pagination-menu-background-color-hover, var(--c-primary-200));
  --_c-pagination-menu-outline-color: var(--c-pagination-menu-outline-color, var(--c-primary-600));

  display: block;
}

c-icon-button {
  --c-icon-button-background-color: var(--_c-pagination-button-active-background-color);
  --c-icon-button-background-color-hover: var(--_c-pagination-button-active-background-color-hover);
  --c-icon-button-text-color: var(--_c-pagination-button-active-text-color);
  --c-icon-button-text-background-color: var(--_c-pagination-button-background-color);
  --c-icon-button-text-background-color-hover: var(--_c-pagination-button-background-color-hover);
  --c-icon-button-text-text-color: var(--_c-pagination-button-text-color);
}

c-menu {
  --c-menu-text-color: var(--_c-pagination-menu-text-color);
  --c-menu-text-color-active: var(--_c-pagination-menu-text-color-active);
  --c-menu-background-color-hover: var(--_c-pagination-menu-background-color-hover);
  --c-menu-outline-color: var(--_c-pagination-menu-outline-color);
}

span {
  font-size: 14px;
  text-align: right;
  white-space: nowrap;
}

.range {
  min-width: 132px;
}

nav {
  align-items: center;
  display: flex;
  flex-wrap: wrap;
  gap: 0 24px;
  justify-content: center;
  width: 100%;
}

ul {
  align-items: center;
  display: flex;
  gap: 4px;
  justify-content: center;
  list-style: none;
  margin: 0;
  padding: 0;
}

.c-pagination__details {
  color: var(--_c-pagination-text-color);
  align-items: center;
  display: flex;
  flex-wrap: wrap;
  flex: auto;
  justify-content: space-between;
}

.c-pagination__items-per-page {
  color: var(--_c-pagination-text-color);
  font-size: 14px;
  text-align: right;
  white-space: nowrap;
  display: flex;
  align-items: center;
  gap: 4px;
}

:host(.c-pagination--simple) ul {
  flex: 1;
  justify-content: flex-end;
}

:host(.c-pagination--small) ul {
  gap: 2px;
}

.visuallyhidden {
  border: 0;
  clip: rect(0 0 0 0);
  height: 1px;
  margin: -1px;
  overflow: hidden;
  padding: 0;
  position: absolute;
  white-space: nowrap;
  width: 1px;
}
</style>

// packages/csc-ui/src/components/c-pagination/c-pagination.tsx
import {
  Component,
  h,
  Host,
  Prop,
  Event,
  EventEmitter,
  State,
  Watch,
} from '@stencil/core';
import { mdiChevronLeft, mdiChevronRight, mdiDotsHorizontal } from '@mdi/js';
import { CMenuOption, CPaginationOptions } from '../../types';

/**
 * @group Navigation
 */

@Component({
  tag: 'c-pagination',
  styleUrl: 'c-pagination.scss',
  shadow: true,
})
export class CPagination {
  /**
   * Object containing values that are needed for pagination.
   *
   * Note! startFrom and endTo are assigned automatically to the object based on other values
   */
  @Prop() value: CPaginationOptions = {
    itemCount: 0,
  };

  /**
   * Hide details (per page dropdown and the 'x - y of n pages' text)
   */
  @Prop() hideDetails = false;

  /**
   * Hide page number buttons
   */
  @Prop() simple = false;

  /**
   * Hide details (per page dropdown and the 'x - y of n pages' text)
   */
  @Prop() size: 'default' | 'small' = 'default';

  @State() private _currentPage;

  @State() private _itemsPerPage;

  @State() private _pageSizes;

  @State() private _totalVisible;

  /**
   * Triggered when values are changed
   */
  @Event({ bubbles: false })
  changeValue: EventEmitter<CPaginationOptions>;

  /**
   * Hide range indicator
   */
  @Prop() hideRange = false;

  @State() tick = '';

  @Watch('value')
  valueHandler(value: CPaginationOptions, oldValue: CPaginationOptions) {
    if (this._isEqual(value, oldValue)) return;

    requestAnimationFrame(() => {
      this._setRange();
    });
  }

  private _isEqual(options1: CPaginationOptions, options2: CPaginationOptions) {
    const keys1 = Object.keys(options1 || {});
    const keys2 = Object.keys(options2 || {});

    if (keys1.length !== keys2.length) {
      return false;
    }

    for (const key of keys1) {
      if (options1[key] !== options2[key]) {
        return false;
      }
    }

    return true;
  }

  componentWillLoad() {
    this._setRange();
  }

  private _textContent = {
    itemsPerPageText: 'Items per page:',
    nextPage: 'Next page',
    prevPage: 'Previous page',
  };

  private _getText(key: string) {
    const source = this.value.textOverrides?.[key]
      ? this.value.textOverrides
      : this._textContent;

    return source[key];
  }

  private _setRange() {
    if (!this.value) return;

    this._currentPage = this.value.currentPage || 1;

    this._itemsPerPage = this.value.itemsPerPage || 25;

    this._totalVisible = this.value.totalVisible || 7;

    this._pageSizes = this.value.pageSizes || [5, 25, 50, 100];

    this.value.startFrom =
      this._currentPage * this._itemsPerPage - this._itemsPerPage;

    this.value.endTo = this._currentPage * this._itemsPerPage - 1;

    this.changeValue.emit(this.value);
  }

  private _buttons: HTMLLIElement[] = [];

  private _valueChangeHandler() {
    this.value.currentPage = this._currentPage;

    this.value.itemsPerPage = this._itemsPerPage;

    this._setRange();
  }

  private _renderMenu() {
    const pageSizes: CMenuOption[] = this._pageSizes.map((i) => ({
      name: i.toString(),
      action: () => {
        this._itemsPerPage = i;
        this._currentPage = 1;
        this._valueChangeHandler();
      },
    }));

    const onMenuClick = (event) => {
      event.stopPropagation();
    };

    return (
      <div class="c-pagination__items-per-page">
        {this._getText('itemsPerPageText')}

        <c-menu items={pageSizes} onClick={onMenuClick}>
          <div>
            <span class="items-per-page">{this._itemsPerPage}</span>
          </div>
        </c-menu>
      </div>
    );
  }

  private _getTotalPages() {
    return Math.ceil(this.value.itemCount / this._itemsPerPage);
  }

  private _increasePageNumber = () => {
    if (this._currentPage < this._getTotalPages()) {
      this._currentPage += 1;
      this._valueChangeHandler();
    }
  };

  private _decreasePageNumber = () => {
    if (this._currentPage > 1) {
      this._currentPage -= 1;
      this._valueChangeHandler();
    }
  };

  private _setPage(number) {
    this._currentPage = number;
    this._valueChangeHandler();
  }

  private _getRange() {
    if (this.hideRange || !this.value.itemCount) return;

    const end = Math.min(
      this._currentPage * this._itemsPerPage,
      this.value.itemCount,
    );
    const start = this.value.startFrom + 1;

    const pageTextOverride = this.value.textOverrides?.pageText;

    let parsedPageTextOverride;

    if (pageTextOverride) {
      parsedPageTextOverride = pageTextOverride({
        start: start,
        end: end,
        count: this.value.itemCount,
      });
    }

    return pageTextOverride
      ? parsedPageTextOverride
      : `${start} - ${end} of ${this.value.itemCount} items`;
  }

  private _getArrowLeft(size) {
    return (
      <li>
        <c-icon-button
          aria-disabled={this.value.currentPage <= 1 ? 'true' : 'false'}
          aria-label={`${this._getText('prevPage')}`}
          disabled={this.value.currentPage <= 1}
          size={size}
          text
          onClick={this._decreasePageNumber}
        >
          <span class="visuallyhidden">{this._getText('prevPage')}</span>

          <c-icon path={mdiChevronLeft}></c-icon>
        </c-icon-button>
      </li>
    );
  }

  private _getArrowRight(size) {
    return (
      <li>
        <c-icon-button
          aria-disabled={
            this.value.currentPage >= this._getTotalPages() ? 'true' : 'false'
          }
          aria-label={`${this._getText('nextPage')}`}
          disabled={this.value.currentPage >= this._getTotalPages()}
          size={size}
          text
          onClick={this._increasePageNumber}
        >
          <span class="visuallyhidden">{this._getText('nextPage')}</span>

          <c-icon path={mdiChevronRight}></c-icon>
        </c-icon-button>
      </li>
    );
  }

  private _button(number, size) {
    const params = {
      text: this._currentPage !== number,
      onClick: () => this._setPage(number),
      size,
    };

    if (this._currentPage === number) {
      params['aria-current'] = 'page';
    }

    const pageOfTextOverride = this.value.textOverrides?.pageOfText;

    let parsedPageOfTextOverride;

    if (pageOfTextOverride) {
      parsedPageOfTextOverride = pageOfTextOverride({
        pageNumber: number,
        count: this._getTotalPages(),
      });
    }

    return (
      <li>
        <c-icon-button {...params}>
          <span
            aria-label={
              pageOfTextOverride
                ? parsedPageOfTextOverride
                : `page ${number} of ${this._getTotalPages()}`
            }
          >
            {number}
          </span>
        </c-icon-button>
      </li>
    );
  }

  private _addButton(number, size) {
    this._buttons.push(this._button(number, size));
  }

  private _addSeparator(size) {
    this._buttons.push(
      <li>
        <c-icon-button
          aria-disabled="true"
          size={size}
          tabindex="-1"
          role="separator"
          disabled
          text
        >
          <svg width="16" height="16" viewBox="0 0 24 24">
            <path d={mdiDotsHorizontal} />
          </svg>
        </c-icon-button>
      </li>,
    );
  }

  private _addButtons(buttonStart, buttonCount, size) {
    if (buttonStart > 1) {
      this._addButton(1, size);
      this._addSeparator(size);
    }

    for (let index = 1; index < buttonCount; index++) {
      this._addButton(buttonStart + index, size);
    }

    const allPagesVisible = this._getTotalPages() <= this._totalVisible;

    if (
      (this._currentPage < this._totalVisible - 1 ||
        this._currentPage < this._getTotalPages() - this._totalVisible + 4) &&
      !allPagesVisible
    ) {
      this._addSeparator(size);
    }
  }

  private _getPageButtons(size) {
    this._buttons = [];
    let buttonStart = 0;
    let buttonCount = this._getTotalPages() + 1;
    const morePagesThanVisible = this._getTotalPages() > this._totalVisible;

    if (morePagesThanVisible) {
      if (this._currentPage < this._totalVisible - 2) {
        buttonCount = this._totalVisible - 1;
      } else if (
        this._currentPage <
        this._getTotalPages() - this._totalVisible + 4
      ) {
        buttonStart = Math.ceil(this._currentPage - this._totalVisible / 2) + 1;
        buttonCount = this._totalVisible - 3;
      } else {
        buttonStart = this._getTotalPages() - this._totalVisible + 2;
        buttonCount = this._totalVisible - 2;
      }
    }

    this._addButtons(buttonStart, buttonCount, size);

    if (morePagesThanVisible) {
      this._buttons.push(this._button(this._getTotalPages(), size));
    }

    return this._buttons;
  }

  private _renderPaginationButtons() {
    if (!this.value.itemCount) return '';

    const buttonsize = this.size === 'small' ? 'x-small' : 'small';

    return (
      <ul>
        {this._getArrowLeft(buttonsize)}
        {!this.simple && this._getPageButtons(buttonsize)}
        {this._getArrowRight(buttonsize)}
      </ul>
    );
  }

  render() {
    const classes = {
      'c-pagination': true,
      'c-pagination--small': this.size === 'small',
      'c-pagination--simple': this.simple,
    };

    return (
      <Host class={classes}>
        <nav role="navigation" aria-label="pagination">
          {!this.hideDetails && (
            <div class="c-pagination__details">
              {this._renderMenu()}
              <span class={{ range: !this.simple }}>{this._getRange()}</span>
            </div>
          )}
          {this._renderPaginationButtons()}
        </nav>
      </Host>
    );
  }
}
