// packages/csc-ui-documentation-next/app/examples/c-button-group/mandatory.react.tsx
// @ts-nocheck — documentation code sample; shown as text, never compiled here
import { useState } from 'react';
import { CButton, CButtonGroup } from '@cscfi/csc-ui-next-react';

export const Mandatory = () => {
  const [align, setAlign] = useState('left');

  return (
    <div className="example-row">
      <CButtonGroup
        label="Alignment"
        mandatory
        value={align}
        onChange={(event) => setAlign(event.detail as string)}
      >
        <CButton value="left">Left</CButton>
        <CButton value="center">Center</CButton>
        <CButton value="right">Right</CButton>
      </CButtonGroup>

      <p>Selected: {align} — the active button cannot be toggled off</p>
    </div>
  );
};

// packages/csc-ui-documentation-next/app/examples/c-button-group/mandatory.vue
<template>
  <div class="example-row">
    <c-button-group v-model="align" label="Alignment" mandatory>
      <c-button value="left">Left</c-button>

      <c-button value="center">Center</c-button>

      <c-button value="right">Right</c-button>
    </c-button-group>

    <span>Selected: {{ align }} — the active button cannot be toggled off</span>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const align = ref('left');
</script>
