// packages/csc-ui-documentation/app/examples/c-button-group/multiple.react.tsx
import { CButton, CButtonGroup } from '@cscfi/csc-ui-react';
// @ts-nocheck — documentation code sample; shown as text, never compiled here
import { useState } from 'react';

export const Multiple = () => {
  const [toppings, setToppings] = useState<string[]>(['cheese']);

  return (
    <div className="example-row">
      <CButtonGroup
        label="Toppings"
        multiple
        onChange={(event) => setToppings(event.detail as string[])}
        value={toppings}
      >
        <CButton value="cheese">Cheese</CButton>
        <CButton value="pepperoni">Pepperoni</CButton>
        <CButton value="mushroom">Mushroom</CButton>
      </CButtonGroup>

      <p>Selected: {toppings.length ? toppings.join(', ') : 'none'}</p>
    </div>
  );
};

// packages/csc-ui-documentation-next/app/examples/c-button-group/multiple.vue
<template>
  <div class="example-row">
    <c-button-group v-model="toppings" label="Toppings" multiple>
      <c-button value="cheese">Cheese</c-button>

      <c-button value="pepperoni">Pepperoni</c-button>

      <c-button value="mushroom">Mushroom</c-button>
    </c-button-group>

    <span>Selected: {{ toppings.length ? toppings.join(', ') : 'none' }}</span>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const toppings = ref<string[]>(['cheese']);
</script>
