// packages/csc-ui/documentation/angular/src/app/examples/c-autocomplete/c-autocomplete.component.ts
import { Component, OnInit } from '@angular/core';
import { CAutocompleteItem } from '../../../../../../dist/types/types';
import countries from '../countries.json';
import { mdiEarth } from '@mdi/js';

@Component({
  selector: 'app-c-autocomplete',
  templateUrl: './c-autocomplete.component.html',
  styleUrls: ['./c-autocomplete.component.scss'],
})
export class CAutocompleteComponent implements OnInit {
  // @example-start|angular
  query: any;

  selection = null;

  items: CAutocompleteItem[] = Object.keys(countries)
    .map((key) => ({
      value: key,
      name: countries[key],
    }))
    .sort((a, b) => a.name.localeCompare(b.name));

  addedTags: CAutocompleteItem[] = [];

  get filteredItems() {
    if (!this.query) return this.items;

    return this.items.filter((i) => i.name?.toLowerCase().includes(this.query?.toLowerCase()));
  }

  changeQuery(event) {
    this.query = event.detail;
  }

  addTag() {
    if (!!this.selection) this.addedTags.push(this.selection);

    this.selection = null;
    this.query = null;
  }

  removeTag(index) {
    this.addedTags.splice(index, 1);
  }
  // @example-end

  // @example-start|customMenu
  setValue(event: Event, item: CAutocompleteItem) {
    const autocomplete = document.querySelector(
      '#customListOfCountries',
    ) as HTMLCAutocompleteElement;

    autocomplete.setValue(event, item);
  }
  // @example-end

  // @example-start|returnValue
  searchString: any;

  tags: string[] = [];

  value = '';

  get countries() {
    if (!this.searchString) return this.items;

    return this.items.filter((i) =>
      i.name?.toLowerCase().includes(this.searchString?.toLowerCase()),
    );
  }

  onAddTag() {
    if (!!this.value) this.tags.push(this.value);

    this.value = null;
    this.searchString = null;
  }

  onQueryChange(event) {
    this.searchString = event.detail;
  }
  // @example-end

  constructor() {}

  mdiEarth = mdiEarth;

  ngOnInit(): void {}
}

<app-example title="Usage in Angular" name="angular" component="c-autocomplete">
  <c-row gap="8">
    <c-autocomplete
      id="listOfCountries"
      label="Countries"
      cControl
      hide-details
      [items]="filteredItems"
      [query]="query"
      (changeQuery)="changeQuery($event)"
      [itemsPerPage]="10"
      [(ngModel)]="selection"
      style="flex: 1"
    >
      <c-icon [path]="mdiEarth" slot="pre" size="16"></c-icon>
    </c-autocomplete>

    <c-button (click)="addTag()" (keyup.enter)="addTag()">Add</c-button>
  </c-row>

  <div class="mt-3">
    <c-tag
      *ngFor="let tag of addedTags; let i = index"
      closeable
      (click)="removeTag(i)"
      (keyup.enter)="removeTag(i)"
    >
      {{ tag.name }}
    </c-tag>
  </div>
</app-example>

<app-example title="Usage with 'return-value'" name="returnValue" component="c-autocomplete" rows>
  <c-row gap="8">
    <c-autocomplete
      [(ngModel)]="value"
      [items]="countries"
      [query]="searchString"
      (changeQuery)="onQueryChange($event)"
      [itemsPerPage]="10"
      label="Countries"
      return-value
      hide-details
      cControl
    ></c-autocomplete>
    <c-button (click)="onAddTag()" (keyup.enter)="onAddTag()">Add</c-button>
  </c-row>

  <p style="margin: 16px 0 0">
    Added values:
    <c-tag flat>{{ tags.length }}</c-tag>
  </p>
  <ul>
    <li *ngFor="let tag of tags">
      {{ tag }}
    </li>
    <li *ngIf="!tags.length">No added values</li>
  </ul>
</app-example>

<app-example title="Usage with custom menu items" name="customMenu" component="c-autocomplete">
  <c-row gap="8">
    <c-autocomplete
      id="customListOfCountries"
      label="Countries"
      cControl
      hide-details
      [items]="filteredItems"
      [query]="query"
      (changeQuery)="changeQuery($event)"
      [itemsPerPage]="3"
      [(ngModel)]="selection"
      style="flex: 1"
      [customMenu]="true"
    >
      <c-icon [path]="mdiEarth" slot="pre" size="16"></c-icon>

      <div
        *ngFor="let item of filteredItems; let i = index"
        slot="customMenu"
        (click)="setValue($event, item)"
      >
        <span>
          <b>Country {{ i + 1 }}</b>
        </span>
        <p>{{ item.name }}</p>
      </div>
    </c-autocomplete>
  </c-row>
</app-example>

// packages/csc-ui-documentation/components/_examples/CAutocomplete.vue
<template>
  <component-example name="basic" rows>
    <template #title>Basic usage</template>

    <c-row gap="8">
      <c-autocomplete
        id="listOfCountries"
        v-model="selection"
        v-control
        label="Countries"
        hide-details
        :items="filteredItems"
        :query="query"
        :items-per-page="10"
        style="flex: 1"
        @input="changeQuery($event)"
      >
        <c-icon slot="pre" :path="mdiEarth" size="16"></c-icon>
      </c-autocomplete>

      <pre>{{ selection }} {{ query }}</pre>

      <c-button @click="addTag()" @keyup.enter="addTag()">Add</c-button>
    </c-row>

    <c-tags class="mt-3">
      <c-tag
        v-for="(tag, index) of addedTags"
        :key="index"
        closeable
        @click="removeTag(index)"
        @keyup.enter="removeTag(index)"
      >
        {{ tag.name }}
      </c-tag>
    </c-tags>
  </component-example>

  <component-example name="returnValue" rows>
    <template #title>Usage with 'return-value'</template>

    <c-row gap="8">
      <c-autocomplete
        v-model="value"
        v-control
        label="Countries"
        hide-details
        :items="countryList"
        :query="searchString"
        :items-per-page="10"
        return-value
        @input="onQueryChange($event)"
      >
        <c-icon slot="pre" :path="mdiEarth" size="16"></c-icon>
      </c-autocomplete>

      <c-button @click="onAddTag()" @keyup.enter="onAddTag()">Add</c-button>
    </c-row>

    <p style="margin: 16px 0 0">
      Added values:
      <c-tag flat>{{ tags.length }}</c-tag>
    </p>
    <ul>
      <li v-for="tag in tags" :key="tag">
        {{ tag }}
      </li>

      <li v-if="!tags.length">No added values</li>
    </ul>
  </component-example>

  <component-example name="customMenu" rows>
    <template #title>Usage with custom menu items</template>

    <c-row gap="8">
      <c-autocomplete
        ref="autocomplete"
        v-model="selectionCustomMenu"
        v-control
        label="Countries"
        hide-details
        :items="filteredItemsCustomMenu"
        :query="queryCustomMenu"
        :items-per-page="10"
        :custom-menu="true"
        style="flex: 1"
        @input="changeQuery($event)"
      >
        <c-icon slot="pre" :path="mdiEarth" size="16"></c-icon>

        <c-option
          v-for="(item, index) in filteredItemsCustomMenu"
          :key="index"
          :value="item.value"
          :name="item.name"
        >
          <c-row align="center" gap="16">
            <c-tag active flat>{{ item.value }}</c-tag>
            <p>{{ item.name }}</p>
          </c-row>
        </c-option>
      </c-autocomplete>
    </c-row>
  </component-example>
</template>

<script setup lang="ts">
// @example-start|basic|returnValue|customMenu
import { ref, computed } from 'vue';
import { mdiEarth } from '@mdi/js';
import { CAutocompleteItem } from '@cscfi/csc-ui';
import countries from '../data/countries.json';
// @example-end

// @example-start|basic|customMenu
const items = computed<CAutocompleteItem[]>(() =>
  Object.keys(countries)
    .map((key) => ({
      value: key,
      name: countries[key as keyof typeof countries],
    }))
    .sort((a, b) => a.name.localeCompare(b.name)),
);

const filteredItems = computed(() => {
  if (!query.value) return items.value;

  return items.value.filter(
    (i) => i.name?.toLowerCase().includes(query.value?.toLowerCase()),
  );
});

const selection = ref();

const query = ref('');

const changeQuery = (event: InputEvent) => {
  query.value = (event.target as HTMLCAutocompleteElement).query;
};
// @example-end

// @example-start|basic
const addedTags = ref<CAutocompleteItem[]>([]);

const addTag = () => {
  if (selection.value) addedTags.value.push(selection.value);

  selection.value = null;
  query.value = '';
};

const removeTag = (index: number) => {
  addedTags.value.splice(index, 1);
};
// @example-end

// @example-start|returnValue
const tags = ref<string[]>([]);

const value = ref('');

const searchString = ref<string>('');

const countryList = computed(() => {
  if (!searchString.value) return items.value;

  return items.value.filter(
    (i) => i.name?.toLowerCase().includes(searchString.value?.toLowerCase()),
  );
});

const onAddTag = () => {
  if (value.value) tags.value.push(value.value);

  value.value = '';
  searchString.value = '';
};

const onQueryChange = (event: InputEvent) => {
  searchString.value = (event.target as HTMLCAutocompleteElement).query;
};
// @example-end

// @example-start|customMenu
const autocomplete = ref<HTMLCAutocompleteElement | null>();

// const setValue = (event: Event, item: CAutocompleteItem) => {
//   autocomplete.value?.setValue(event, item);
// };

const selectionCustomMenu = ref();

const queryCustomMenu = ref('');

const filteredItemsCustomMenu = computed(() => {
  if (!queryCustomMenu.value) return items.value;

  return items.value.filter(
    (i) => i.name?.toLowerCase().includes(queryCustomMenu.value?.toLowerCase()),
  );
});

// @example-end
</script>

<style lang="scss">
div[slot='customMenu'] {
  cursor: pointer;
  padding: 5px 10px;
  p {
    margin: 0;
  }
}

div[aria-selected='true'],
div[slot='customMenu']:hover {
  background-color: var(--c-primary-200);
}
</style>
