// packages/csc-ui/src/components/c-status/c-status.tsx
import { Component, Host, h, Prop } from '@stencil/core';

/**
 * @group Indicators
 * @slot Default slot - Status text
 */
@Component({
  tag: 'c-status',
  styleUrl: 'c-status.scss',
  shadow: true,
})
export class CStatus {
  /**
   * Status type
   */
  @Prop() type?: 'info' | 'warning' | 'error' | 'success';

  render() {
    const classes = {
      'c-status': true,
      ...(!!this.type && { [`c-status--${this.type}`]: this.type }),
    };

    return (
      <Host>
        <div class={classes}>
          <slot></slot>
        </div>
      </Host>
    );
  }
}

// packages/csc-ui-documentation/components/_examples/CStatus.vue
<template>
  <c-row gap="8">
    <c-status>Default</c-status>
    <c-status type="info">Info</c-status>
    <c-status type="warning">Warning</c-status>
    <c-status type="error">Error</c-status>
    <c-status type="success">Success</c-status>
  </c-row>
</template>

<script setup lang="ts"></script>

<style lang="scss"></style>
