// packages/csc-ui-documentation-next/app/examples/c-tag/closeable.react.tsx
// @ts-nocheck — documentation code sample; shown as text, never compiled here
import { useState } from 'react';
import { CTag, CTags } from '@cscfi/csc-ui-next-react';

export const Closeable = () => {
  const [topics, setTopics] = useState(['Biosciences', 'Chemistry', 'Physics']);

  const remove = (topic: string) => {
    setTopics((current) => current.filter((t) => t !== topic));
  };

  return (
    <div className="example-row">
      <CTags>
        {topics.map((topic) => (
          <CTag key={topic} closeable onClose={() => remove(topic)}>
            {topic}
          </CTag>
        ))}
      </CTags>
    </div>
  );
};

// packages/csc-ui-documentation-next/app/examples/c-tag/closeable.vue
<template>
  <div class="example-row">
    <c-tags>
      <c-tag
        v-for="topic in topics"
        :key="topic"
        closeable
        @close="remove(topic)"
      >
        {{ topic }}
      </c-tag>
    </c-tags>
  </div>
</template>

<script setup lang="ts">
const topics = ref(['Biosciences', 'Chemistry', 'Physics']);

const remove = (topic: string) => {
  topics.value = topics.value.filter((t) => t !== topic);
};
</script>
