// packages/csc-ui-documentation-next/app/examples/c-menu-item/submenu.vue
<template>
  <div class="example-row">
    <c-menu @select="onSelect">
      <c-button slot="trigger" ghost>
        Export
        <c-icon :path="mdiChevronDown" />
      </c-button>

      <c-menu-item value="documents">
        Documents

        <c-menu-item slot="submenu" value="pdf">
          <c-icon :path="mdiFilePdfBox" />
          PDF
        </c-menu-item>

        <c-menu-item slot="submenu" value="docx">
          <c-icon :path="mdiFileDocument" />
          Word document
        </c-menu-item>
      </c-menu-item>

      <c-menu-item value="settings">Export settings…</c-menu-item>
    </c-menu>

    <span>Selected: {{ selected ?? '—' }}</span>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

import { mdiChevronDown, mdiFileDocument, mdiFilePdfBox } from '@mdi/js';

const selected = ref<null | string>(null);

const onSelect = (event: Event) => {
  selected.value = (event as CustomEvent<{ value: string }>).detail.value;
};
</script>

// packages/csc-ui-documentation-next/app/examples/c-menu-item/submenu.react.tsx
// @ts-nocheck — documentation code sample; shown as text, never compiled here
import { useState } from 'react';
import { mdiChevronDown, mdiFileDocument, mdiFilePdfBox } from '@mdi/js';
import { CButton, CIcon, CMenu, CMenuItem } from '@cscfi/csc-ui-next-react';

export const Submenu = () => {
  const [selected, setSelected] = useState<null | string>(null);

  return (
    <div className="example-row">
      <CMenu onSelect={(event) => setSelected(event.detail.value as string)}>
        <CButton slot="trigger" ghost>
          Export
          <CIcon path={mdiChevronDown} />
        </CButton>

        <CMenuItem value="documents">
          Documents
          <CMenuItem slot="submenu" value="pdf">
            <CIcon path={mdiFilePdfBox} />
            PDF
          </CMenuItem>
          <CMenuItem slot="submenu" value="docx">
            <CIcon path={mdiFileDocument} />
            Word document
          </CMenuItem>
        </CMenuItem>

        <CMenuItem value="settings">Export settings…</CMenuItem>
      </CMenu>

      <p>Selected: {selected ?? '—'}</p>
    </div>
  );
};
