// packages/csc-ui-documentation/app/examples/c-table/responsive.vue
<template>
  <div>
    <!-- Below the breakpoint each row becomes a card with header labels -->
    <c-table responsive mobile-breakpoint="800">
      <table>
        <thead>
          <tr>
            <th>Name</th>

            <th>Role</th>

            <th>Email</th>
          </tr>
        </thead>

        <tbody>
          <tr>
            <td>Anna Virtanen</td>

            <td>Researcher</td>

            <td>anna.virtanen@example.fi</td>
          </tr>

          <tr>
            <td>Mikko Korhonen</td>

            <td>Data engineer</td>

            <td>mikko.korhonen@example.fi</td>
          </tr>
        </tbody>
      </table>
    </c-table>
  </div>
</template>

// packages/csc-ui-documentation/app/examples/c-table/responsive.react.tsx
// @ts-nocheck — documentation code sample; shown as text, never compiled here
import { CTable } from '@cscfi/csc-ui-react';

export const Responsive = () => (
  <div>
    {/* Below the breakpoint each row becomes a card with header labels */}
    <CTable mobileBreakpoint={800} responsive>
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Role</th>
            <th>Email</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Anna Virtanen</td>
            <td>Researcher</td>
            <td>anna.virtanen@example.fi</td>
          </tr>
          <tr>
            <td>Mikko Korhonen</td>
            <td>Data engineer</td>
            <td>mikko.korhonen@example.fi</td>
          </tr>
        </tbody>
      </table>
    </CTable>
  </div>
);
