// packages/csc-ui-documentation/components/examples/CLoginButtons.vue
<template>
  <component-example name="basic">
    <template #title>Basic usage</template>

    <c-card style="width: 600px">
      <c-card-title>Select authentication provider</c-card-title>

      <c-card-content>
        <c-login-buttons>
          <c-login-button src="/img/csc-logo.png">Provider 1</c-login-button>

          <c-login-button src="/img/csc-logo.png">Provider 2</c-login-button>

          <c-login-button src="/img/csc-logo.png">Provider 3</c-login-button>

          <c-login-button src="/img/csc-logo.png">Provider 4</c-login-button>
        </c-login-buttons>
      </c-card-content>
    </c-card>
  </component-example>
</template>

<script setup lang="ts"></script>

<style lang="scss"></style>

// packages/csc-ui/documentation/angular/src/app/examples/c-login-buttons/c-login-buttons.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-c-login-buttons',
  templateUrl: './c-login-buttons.component.html',
  styleUrls: ['./c-login-buttons.component.scss'],
})
export class CLoginButtonsComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}
}

<app-example title="Basic usage" name="basic" component="c-login-buttons" cols>
  <c-card style="width: 600px">
    <c-card-title>Select authentication provider</c-card-title>

    <c-card-content>
      <c-login-buttons>
        <c-login-button src="assets/csc-logo.png">Provider 1</c-login-button>

        <c-login-button src="assets/csc-logo.png">Provider 2</c-login-button>

        <c-login-button src="assets/csc-logo.png">Provider 3</c-login-button>

        <c-login-button src="assets/csc-logo.png">Provider 4</c-login-button>
      </c-login-buttons>
    </c-card-content>
  </c-card>
</app-example>
