// packages/csc-ui-documentation/app/examples/c-toasts/placement.react.tsx
// @ts-nocheck — documentation code sample; shown as text, never compiled here
import { useRef, useState } from 'react';
import { CButton, COption, CSelect, CToasts } from '@cscfi/csc-ui-react';
import type { CToastsElement } from '@cscfi/csc-ui';

export const Placement = () => {
  const toasts = useRef<CToastsElement>(null);

  const [vertical, setVertical] = useState('bottom');

  const [horizontal, setHorizontal] = useState('center');

  const notify = () => {
    toasts.current?.addToast({
      type: 'info',
      title: 'Notification',
      message: `Placed at ${vertical} ${horizontal}.`,
      progress: true,
    });
  };

  return (
    <div className="example-row">
      <CSelect
        value={vertical}
        label="Vertical"
        onChangeValue={(event) => setVertical(event.detail as string)}
      >
        <COption name="Bottom" value="bottom">
          Bottom
        </COption>
        <COption name="Top" value="top">
          Top
        </COption>
      </CSelect>

      <CSelect
        value={horizontal}
        label="Horizontal"
        onChangeValue={(event) => setHorizontal(event.detail as string)}
      >
        <COption name="Left" value="left">
          Left
        </COption>
        <COption name="Center" value="center">
          Center
        </COption>
        <COption name="Right" value="right">
          Right
        </COption>
      </CSelect>

      <CButton onClick={notify}>Show toast</CButton>

      <CToasts ref={toasts} horizontal={horizontal} vertical={vertical} />
    </div>
  );
};

// packages/csc-ui-documentation/app/examples/c-toasts/placement.vue
<template>
  <div class="example-row">
    <c-select v-model="vertical" label="Vertical">
      <c-option name="Bottom" value="bottom">Bottom</c-option>

      <c-option name="Top" value="top">Top</c-option>
    </c-select>

    <c-select v-model="horizontal" label="Horizontal">
      <c-option name="Left" value="left">Left</c-option>

      <c-option name="Center" value="center">Center</c-option>

      <c-option name="Right" value="right">Right</c-option>
    </c-select>

    <c-button @click="notify()">Show toast</c-button>

    <c-toasts ref="toasts" :horizontal="horizontal" :vertical="vertical" />
  </div>
</template>

<script setup lang="ts">
import { ref, useTemplateRef } from 'vue';

interface ToastMessage {
  duration?: number;
  message: string;
  persistent?: boolean;
  progress?: boolean;
  title?: string;
  type?: 'error' | 'info' | 'success' | 'warning';
}

type CToastsElement = HTMLElement & {
  addToast: (message: ToastMessage) => void;
};

const toasts = useTemplateRef<CToastsElement>('toasts');

const vertical = ref('bottom');

const horizontal = ref('center');

const notify = () => {
  toasts.value?.addToast({
    type: 'info',
    title: 'Notification',
    message: `Placed at ${vertical.value} ${horizontal.value}.`,
    progress: true,
  });
};
</script>
