// packages/csc-ui-documentation-next/app/examples/c-slider/ticks.vue
<template>
  <div>
    <c-slider
      :value.prop="cores"
      label="CPU cores"
      labels
      max="8"
      min="0"
      segments="8"
      step="1"
      ticks
      unit=""
      @changeValue="onChange"
    />
  </div>
</template>

<script setup lang="ts">
const cores = ref(2);

const onChange = (event: Event) => {
  cores.value = (event as CustomEvent<number>).detail;
};
</script>

// packages/csc-ui-documentation/app/examples/c-slider/ticks.react.tsx
// @ts-nocheck — documentation code sample; shown as text, never compiled here
import { useState } from 'react';
import { CSlider } from '@cscfi/csc-ui-react';

export const Ticks = () => {
  const [cores, setCores] = useState(2);

  return (
    <div>
      <CSlider
        value={cores}
        label="CPU cores"
        labels
        max="8"
        min="0"
        segments="8"
        step="1"
        ticks
        unit=""
        onChangeValue={(event) => setCores(event.detail as number)}
      />
    </div>
  );
};
