// packages/csc-ui/src/components/c-modal/c-modal.tsx
import {
  Component,
  h,
  Prop,
  Event,
  EventEmitter,
  State,
  Watch,
  Element,
} from '@stencil/core';

/**
 * @group Popups
 */
@Component({
  tag: 'c-modal',
  styleUrl: 'c-modal.scss',
  shadow: true,
})
export class CModal {
  @Element() el: HTMLCModalElement;

  private _dialog?: HTMLDialogElement;

  /**
   * Is the modal visible
   */
  @Prop() value = false;

  /**
   * Dismissed when touching/clicking outside the content
   */
  @Prop() dismissable = false;

  /**
   * Width of the dialog. Numeric value is considered as pixel value (400 -> 400px)
   *
   */
  @Prop() width: string | number = 600;

  /**
   * Z-index of the modal
   */
  @Prop() zIndex = 10;

  /**
   * Disable backdrop blur effect
   */
  @Prop() disableBackdropBlur = false;

  /**
   * Triggered when value is changed
   */
  @Event({ bubbles: false })
  changeValue: EventEmitter<boolean>;

  @State() innerValue = false;

  @State() animateModal = false;

  // Not used inside c-main
  @State() standaloneMode = false;

  private _debounce = null;

  private _animationsDisabled = false;

  @Watch('value')
  onValueChange(value: boolean) {
    if (value) {
      this._handleShow();

      return;
    }

    this._handleClose();
  }

  private _backdropElement: HTMLCBackdropElement;

  private _handleBackdrop = () => {
    const cMain = document.body.querySelector('c-main');

    if (!cMain) {
      this.standaloneMode = true;

      return;
    }

    this.standaloneMode = false;

    this._backdropElement ||= cMain.shadowRoot.querySelector('c-backdrop');

    if (!this._backdropElement) {
      return;
    }

    this._backdropElement.setAttribute(
      'disable-backdrop-blur',
      this.disableBackdropBlur.toString(),
    );

    this._backdropElement?.shadowRoot
      ?.querySelector('.c-backdrop')
      ?.classList.remove('closing');
  };

  private _handleShow = () => {
    requestAnimationFrame(() => {
      this._handleBackdrop();

      if (!this._animationsDisabled) {
        this._dialog?.addEventListener('animationend', this._onDialogOpened);

        this._dialog?.classList.add('opening');

        this._backdropElement?.shadowRoot
          ?.querySelector('.c-backdrop')
          ?.classList.add('opening');
      }

      this._dialog?.showModal();
    });
  };

  private _onDialogOpened = () => {
    this._dialog?.removeEventListener('animationend', this._onDialogOpened);
    this._dialog?.classList.remove('opening');
  };

  private _handleClose = () => {
    if (this._animationsDisabled) {
      this._onDialogClosed();

      return;
    }

    this._dialog?.addEventListener('animationend', this._onDialogClosed);

    this._dialog?.classList.add('closing');

    const numberOfOpenModals = this._getOpenDialogsFromCustomElements();

    if (numberOfOpenModals === 1) {
      this._backdropElement?.shadowRoot
        ?.querySelector('.c-backdrop')
        ?.classList.remove('opening');

      this._backdropElement?.shadowRoot
        ?.querySelector('.c-backdrop')
        ?.classList.add('closing');
    }
  };

  private _onDialogClosed = () => {
    if (!this._animationsDisabled) {
      this._dialog?.removeEventListener('animationend', this._onDialogClosed);

      this._dialog?.classList.remove('closing');

      this._backdropElement?.shadowRoot
        ?.querySelector('.c-backdrop')
        ?.classList.remove('closing');
    }

    this._dialog?.close();

    if (!document.fullscreenElement) return;

    document.exitFullscreen();
  };

  private _handleClickOutside = () => {
    this._dialog.addEventListener('click', (e) => {
      if (e.clientX === 0 && e.clientY === 0) return;

      const dialogDimensions = this._dialog.getBoundingClientRect();

      if (
        e.clientX < dialogDimensions.left ||
        e.clientX > dialogDimensions.right ||
        e.clientY < dialogDimensions.top ||
        e.clientY > dialogDimensions.bottom
      ) {
        if (!this.dismissable) {
          this._dialog.classList.add('nudging');

          if (this._debounce !== null) {
            clearTimeout(this._debounce);
            this._debounce = null;
          }

          this._debounce = window.setTimeout(() => {
            this._dialog.classList.remove('nudging');

            this._debounce = null;
          }, 150);

          return;
        }

        this._handleClose();
        this.changeValue.emit(false);
      }
    });
  };

  private _handleKeyDown = (e) => {
    if (e.keyCode === 27) {
      e.preventDefault();
      this._handleClose();
      this.changeValue.emit(false);
    }
  };

  private _getOpenDialogsInShadowRoot = (
    shadowRoot: ShadowRoot,
  ): HTMLDialogElement[] => {
    const dialogs = shadowRoot.querySelectorAll(
      'dialog',
    ) as NodeListOf<HTMLDialogElement>;

    return Array.from(dialogs).filter((dialog) => dialog.open);
  };

  private _getOpenDialogsFromCustomElements = (): number => {
    let count = 0;

    const customElements = document.querySelectorAll('c-modal');

    customElements.forEach((element) => {
      if (element.shadowRoot) {
        const openDialogs = this._getOpenDialogsInShadowRoot(
          element.shadowRoot,
        );
        count += openDialogs.length;
      }
    });

    return count;
  };

  componentWillLoad() {
    this.innerValue = this.value;

    const width = isNaN(this.width as number) ? this.width : `${this.width}px`;

    this.el.style.setProperty('--_c-modal-width', `${width}`);
  }

  componentDidLoad() {
    const query = window.matchMedia('(prefers-reduced-motion: reduce)');

    this._animationsDisabled = query.matches;

    this._handleClickOutside();

    if (this.value) {
      this._handleShow();
    }
  }

  disconnectedCallback() {
    const dialogs = document.querySelectorAll('c-dialog');

    if (!dialogs.length) {
      this._handleClose();
    }
  }

  render() {
    const dialogStyle = {
      'z-index': `${this.zIndex}`,
    };

    const classes = {
      'c-modal': true,
      'c-modal--standalone': this.standaloneMode,
      'c-modal--backdrop-blur': !this.disableBackdropBlur,
    };

    return (
      <dialog
        ref={(el) => (this._dialog = el as HTMLDialogElement)}
        style={dialogStyle}
        class={classes}
        onKeyDown={this._handleKeyDown}
      >
        <slot></slot>
      </dialog>
    );
  }
}

// packages/csc-ui-next/src/components/c-modal/CModal.vue
<template>
  <dialog
    ref="dialogEl"
    class="c-modal"
    :class="{
      'c-modal--standalone': standaloneMode,
      'c-modal--backdrop-blur': !disableBackdropBlur,
    }"
    :style="{ zIndex: String(zIndex) }"
    @keydown="onKeyDown"
    @click="onClick"
  >
    <slot />
  </dialog>
</template>

<script setup lang="ts">
import { onMounted, ref, useHost, useTemplateRef, watch } from 'vue';

const props = defineProps({
  value: { type: Boolean, default: false },
  dismissable: { type: Boolean, default: false },
  width: { type: [String, Number], default: 600 },
  zIndex: { type: Number, default: 10 },
  disableBackdropBlur: { type: Boolean, default: false },
});

const host = useHost();
const dispatchValue = (name: string, value: unknown) => {
  host?.dispatchEvent(new CustomEvent(name, { detail: value }));
};

const dialogEl = useTemplateRef<HTMLDialogElement>('dialogEl');
const standaloneMode = ref(false);

let animationsDisabled = false;
let backdropEl: HTMLElement | null = null;
let nudgeTimer: ReturnType<typeof setTimeout> | null = null;

// `c-main` renders a shared `<c-backdrop>` in its shadow root so all
// modals in the page share one dimmer. If the page isn't wrapped in
// `<c-main>` (standalone usage), fall through to the dialog's native
// ::backdrop pseudo-element which we style in CSS.
const resolveBackdrop = () => {
  const cMain = document.body.querySelector('c-main');
  if (!cMain) {
    standaloneMode.value = true;
    return null;
  }
  standaloneMode.value = false;
  if (!backdropEl) {
    backdropEl =
      (cMain.shadowRoot?.querySelector('c-backdrop') as HTMLElement | null) ||
      null;
  }
  backdropEl?.setAttribute(
    'disable-backdrop-blur',
    String(props.disableBackdropBlur),
  );
  const inner = backdropEl?.shadowRoot?.querySelector('.c-backdrop');
  inner?.classList.remove('closing');
  return backdropEl;
};

const openDialog = () => {
  requestAnimationFrame(() => {
    resolveBackdrop();
    if (!animationsDisabled) {
      const onAnimEnd = () => {
        dialogEl.value?.removeEventListener('animationend', onAnimEnd);
        dialogEl.value?.classList.remove('opening');
      };
      dialogEl.value?.addEventListener('animationend', onAnimEnd);
      dialogEl.value?.classList.add('opening');
      backdropEl?.shadowRoot
        ?.querySelector('.c-backdrop')
        ?.classList.add('opening');
    }
    dialogEl.value?.showModal();
  });
};

const closeDialog = () => {
  if (animationsDisabled) {
    finalizeClose();
    return;
  }
  const onAnimEnd = () => {
    dialogEl.value?.removeEventListener('animationend', onAnimEnd);
    finalizeClose();
  };
  dialogEl.value?.addEventListener('animationend', onAnimEnd);
  dialogEl.value?.classList.add('closing');

  requestAnimationFrame(() => {
    // Count modals still open across the page; only remove backdrop
    // when this is the last one closing.
    const customs = document.querySelectorAll('c-modal');
    let openCount = 0;
    customs.forEach((el) => {
      const dialogs = el.shadowRoot?.querySelectorAll('dialog');
      dialogs?.forEach((d) => {
        if ((d as HTMLDialogElement).open) openCount += 1;
      });
    });
    if (openCount <= 1) {
      const inner = backdropEl?.shadowRoot?.querySelector('.c-backdrop');
      inner?.classList.remove('opening');
      inner?.classList.add('closing');
    }
  });
};

const finalizeClose = () => {
  dialogEl.value?.classList.remove('closing');
  backdropEl?.shadowRoot
    ?.querySelector('.c-backdrop')
    ?.classList.remove('closing');
  dialogEl.value?.close();
  if (document.fullscreenElement) document.exitFullscreen();
};

// Backdrop click detection. The native <dialog> swallows clicks on its
// ::backdrop pseudo as clicks on the dialog itself, so we get the
// dialog rect and compare against pointer coords.
const onClick = (e: MouseEvent) => {
  if (e.clientX === 0 && e.clientY === 0) return;
  if (!dialogEl.value) return;
  const rect = dialogEl.value.getBoundingClientRect();
  const outside =
    e.clientX < rect.left ||
    e.clientX > rect.right ||
    e.clientY < rect.top ||
    e.clientY > rect.bottom;
  if (!outside) return;
  if (!props.dismissable) {
    // Non-dismissable: nudge animation to signal "you can't close
    // this", then revert.
    dialogEl.value.classList.add('nudging');
    if (nudgeTimer !== null) clearTimeout(nudgeTimer);
    nudgeTimer = setTimeout(() => {
      dialogEl.value?.classList.remove('nudging');
      nudgeTimer = null;
    }, 150);
    return;
  }
  closeDialog();
  dispatchValue('changeValue', false);
  dispatchValue('update:value', false);
};

const onKeyDown = (e: KeyboardEvent) => {
  if (e.key === 'Escape') {
    e.preventDefault();
    closeDialog();
    dispatchValue('changeValue', false);
    dispatchValue('update:value', false);
  }
};

watch(
  () => props.value,
  (next) => {
    if (next) openDialog();
    else closeDialog();
  },
);

onMounted(() => {
  const query = window.matchMedia('(prefers-reduced-motion: reduce)');
  animationsDisabled = query.matches;

  // Stencil set this on componentWillLoad; we set it once on mount.
  // Numeric width → "Npx", string width → as-is.
  const width =
    typeof props.width === 'number' || !isNaN(Number(props.width))
      ? `${props.width}px`
      : String(props.width);
  host?.style.setProperty('--_c-modal-width', width);

  if (props.value) openDialog();
});
</script>

<style>
dialog.c-modal {
  background-color: transparent;
  border: none;
  color: var(--c-text-body);
  inset: 0;
  margin: auto;
  max-width: calc(100% - 32px);
  overflow: visible;
  padding: 0;
  width: var(--_c-modal-width, 600px);
}

dialog.c-modal:not([open]) {
  pointer-events: none;
  opacity: 0;
}

dialog.c-modal::backdrop {
  background-color: transparent;
}

/* Standalone (no <c-main>): rely on native ::backdrop for the dimmer
 * instead of the shared c-backdrop element. */
dialog.c-modal--standalone::backdrop {
  background-color: rgba(0, 0, 0, 0.5);
}

dialog.c-modal--standalone.c-modal--backdrop-blur::backdrop {
  backdrop-filter: blur(4px);
}

@media (prefers-reduced-motion: no-preference) {
  dialog.nudging {
    animation: c-modal-nudge 0.15s cubic-bezier(0.25, 0.8, 0.25, 1) !important;
  }
  dialog.opening {
    animation: c-modal-open 0.3s cubic-bezier(0.25, 0.8, 0.5, 1) forwards;
  }
  dialog.closing {
    animation: c-modal-close 0.3s cubic-bezier(0.25, 0.8, 0.5, 1) forwards;
  }
}

@keyframes c-modal-nudge {
  0% { transform: scale(1); }
  50% { transform: scale(1.03); }
  100% { transform: scale(1); }
}

@keyframes c-modal-open {
  from { transform: scale(0); }
  to { transform: scale(1); }
}

@keyframes c-modal-close {
  to { transform: scale(0); }
}
</style>
