// packages/csc-ui-documentation/app/examples/c-button-group/on-canvas.react.tsx
// @ts-nocheck — documentation code sample; shown as text, never compiled here
import { useState } from 'react';
import { CButton, CButtonGroup } from '@cscfi/csc-ui-react';

export const OnCanvas = () => {
  const [period, setPeriod] = useState<string | null>('monthly');

  return (
    <div className="example-row">
      <CButtonGroup
        label="Billing period"
        value={period}
        onChange={(event) => setPeriod(event.detail as string | null)}
      >
        <CButton value="monthly">Monthly</CButton>
        <CButton value="yearly">Yearly</CButton>
      </CButtonGroup>
    </div>
  );
};

// packages/csc-ui-documentation/app/examples/c-button-group/on-canvas.vue
<docs>surface: canvas</docs>

<template>
  <div class="example-row">
    <c-button-group v-model="period" label="Billing period">
      <c-button value="monthly">Monthly</c-button>

      <c-button value="yearly">Yearly</c-button>
    </c-button-group>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const period = ref<null | string>('monthly');
</script>
