// packages/csc-ui-documentation/app/examples/c-alert/types.vue
<template>
  <div style="display: grid; gap: 1rem">
    <c-alert>A default alert without a type.</c-alert>

    <c-alert type="info">Your session expires in 15 minutes.</c-alert>

    <c-alert type="success">Your project was created.</c-alert>

    <c-alert type="warning">Your quota is almost full.</c-alert>

    <c-alert type="error">The file could not be uploaded.</c-alert>
  </div>
</template>

// packages/csc-ui-documentation-next/app/examples/c-alert/types.react.tsx
// @ts-nocheck — documentation code sample; shown as text, never compiled here
import { CAlert } from '@cscfi/csc-ui-next-react';

export const Types = () => (
  <div style={{ display: 'grid', gap: '1rem' }}>
    <CAlert>A default alert without a type.</CAlert>

    <CAlert type="info">Your session expires in 15 minutes.</CAlert>

    <CAlert type="success">Your project was created.</CAlert>

    <CAlert type="warning">Your quota is almost full.</CAlert>

    <CAlert type="error">The file could not be uploaded.</CAlert>
  </div>
);
