// packages/csc-ui-documentation/app/examples/c-select/multiple.react.tsx
// @ts-nocheck — documentation code sample; shown as text, never compiled here
import { useState } from 'react';
import { COption, CSelect } from '@cscfi/csc-ui-react';

export const Multiple = () => {
  const [countries, setCountries] = useState<string[]>(['fi', 'se']);

  return (
    <div>
      <CSelect
        value={countries}
        clearable
        hint="Pick as many as you like"
        label="Countries"
        maxTags={3}
        multiple
        onChangeValue={(event) => setCountries(event.detail as string[])}
      >
        <COption name="Finland" value="fi">
          Finland
        </COption>
        <COption name="Sweden" value="se">
          Sweden
        </COption>
        <COption name="Norway" value="no">
          Norway
        </COption>
        <COption name="Denmark" value="dk">
          Denmark
        </COption>
        <COption name="Iceland" value="is">
          Iceland
        </COption>
        <COption name="Estonia" value="ee">
          Estonia
        </COption>
      </CSelect>

      <p>Value: {countries.length ? countries.join(', ') : '[]'}</p>
    </div>
  );
};

// packages/csc-ui-documentation/app/examples/c-select/multiple.vue
<template>
  <div>
    <!-- In multiple mode the value is an array in pick order. Picked options
         show as tags inside the field; `max-tags` folds the rest into one
         "+N more" tag. Backspace in the closed field removes the last tag. -->
    <c-select
      v-model="countries"
      hint="Pick as many as you like"
      label="Countries"
      max-tags="3"
      clearable
      multiple
    >
      <c-option name="Finland" value="fi">Finland</c-option>

      <c-option name="Sweden" value="se">Sweden</c-option>

      <c-option name="Norway" value="no">Norway</c-option>

      <c-option name="Denmark" value="dk">Denmark</c-option>

      <c-option name="Iceland" value="is">Iceland</c-option>

      <c-option name="Estonia" value="ee">Estonia</c-option>
    </c-select>

    <p>Value: {{ countries.length ? countries.join(', ') : '[]' }}</p>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const countries = ref<string[]>(['fi', 'se']);
</script>
