// packages/csc-ui-documentation/app/examples/c-select/select-all.vue
<template>
  <div>
    <!-- `select-all` pins a row at the top of the list that picks every
         enabled option, or unpicks them all once they are all picked. Its
         checkbox reads none, some or all; the disabled option is left alone. -->
    <c-select
      v-model="countries"
      clearable
      hint="Pick some, or all at once"
      label="Countries"
      max-tags="3"
      multiple
      select-all
    >
      <c-option name="Finland" value="fi">Finland</c-option>

      <c-option name="Sweden" value="se">Sweden</c-option>

      <c-option name="Norway" value="no">Norway</c-option>

      <c-option name="Denmark" value="dk">Denmark</c-option>

      <c-option name="Iceland" value="is">Iceland</c-option>

      <c-option name="Faroe Islands" value="fo" disabled>
        Faroe Islands
      </c-option>
    </c-select>

    <p>Value: {{ countries.length ? countries.join(', ') : '[]' }}</p>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const countries = ref<string[]>(['fi']);
</script>

// packages/csc-ui-documentation/app/examples/c-select/select-all.react.tsx
// @ts-nocheck — documentation code sample; shown as text, never compiled here
import { useState } from 'react';
import { COption, CSelect } from '@cscfi/csc-ui-react';

export const SelectAll = () => {
  const [countries, setCountries] = useState<string[]>(['fi']);

  return (
    <div>
      <CSelect
        value={countries}
        clearable
        hint="Pick some, or all at once"
        label="Countries"
        maxTags={3}
        multiple
        selectAll
        onChangeValue={(event) => setCountries(event.detail as string[])}
      >
        <COption name="Finland" value="fi">
          Finland
        </COption>
        <COption name="Sweden" value="se">
          Sweden
        </COption>
        <COption name="Norway" value="no">
          Norway
        </COption>
        <COption name="Denmark" value="dk">
          Denmark
        </COption>
        <COption name="Iceland" value="is">
          Iceland
        </COption>
        <COption name="Faroe Islands" value="fo" disabled>
          Faroe Islands
        </COption>
      </CSelect>

      <p>Value: {countries.length ? countries.join(', ') : '[]'}</p>
    </div>
  );
};
