// packages/csc-ui-documentation/app/examples/c-select/small.vue
<template>
  <div>
    <c-select v-model="country" label="Country" size="small">
      <c-option name="Finland" value="fi">Finland</c-option>

      <c-option name="Sweden" value="se">Sweden</c-option>

      <c-option name="Norway" value="no">Norway</c-option>
    </c-select>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const country = ref<string | null>('fi');
</script>

// packages/csc-ui-documentation/app/examples/c-select/small.react.tsx
import { COption, CSelect } from '@cscfi/csc-ui-react';
// @ts-nocheck — documentation code sample; shown as text, never compiled here
import { useState } from 'react';

export const Small = () => {
  const [country, setCountry] = useState<null | string>('fi');

  return (
    <div>
      <CSelect
        label="Country"
        onChangeValue={(event) => setCountry(event.detail as null | string)}
        size="small"
        value={country}
      >
        <COption name="Finland" value="fi">
          Finland
        </COption>
        <COption name="Sweden" value="se">
          Sweden
        </COption>
        <COption name="Norway" value="no">
          Norway
        </COption>
      </CSelect>
    </div>
  );
};
