// packages/csc-ui-documentation/components/_examples/CSwiper.vue
<template>
  <component-example name="basic" rows>
    <template #title>Basic usage</template>

    <c-swiper v-model="currentTab" v-control>
      <c-swiper-tab
        v-for="(tab, index) in tabs"
        :key="tab.value"
        :active="selectedTab === tab.value"
        :label="tab.label"
        :value="tab.value"
        :disabled="tab.disabled"
        @click="!tab.disabled && selectTab(tab)"
        @keyup.enter="!tab.disabled && selectTab(tab)"
      >
        <c-icon slot="icon" :path="mdiServer"></c-icon>

        Lorem ipsum dolor sit amet, consectetur adipiscing elit.

        <span v-if="index % 2 === 0">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        </span>
      </c-swiper-tab>
    </c-swiper>

    <p class="mt-3">Focused tab: {{ currentTab }}</p>

    <p class="mt-2">Selection: {{ selectionText }}</p>
  </component-example>

  <component-example name="string" rows>
    <template #title>Basic usage (string value)</template>

    <c-swiper v-model="currentTabItem" v-control>
      <c-swiper-tab
        v-for="(tab, index) in tabsItems"
        :key="tab.value"
        :active="selectedTabItem === tab.value"
        :label="tab.label"
        :value="tab.value"
        :disabled="tab.disabled"
        @click="!tab.disabled && selectTabItem(tab)"
        @keyup.enter="!tab.disabled && selectTabItem(tab)"
      >
        <c-icon slot="icon" :path="mdiServer"></c-icon>

        Lorem ipsum dolor sit amet, consectetur adipiscing elit.

        <span v-if="index % 2 === 0">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        </span>
      </c-swiper-tab>
    </c-swiper>

    <p class="mt-3">Focused tab: {{ currentTabItem }}</p>

    <p class="mt-2">Selection: {{ selectionItemText }}</p>
  </component-example>
</template>

<script setup lang="ts">
// @example-start|basic|string
import { ref } from 'vue';
import { mdiServer } from '@mdi/js';
// @example-end

// @example-start|basic
type Tab = {
  label: string;
  value: number;
  disabled: boolean;
};

const currentTab = ref('');

const selectedTab = ref(1);

const selectionText = ref('Tab "One" selected');

const tabs: Tab[] = [
  { label: 'One', value: 1, disabled: false },
  { label: 'Two', value: 2, disabled: false },
  { label: 'Three', value: 3, disabled: false },
  { label: 'Four', value: 4, disabled: true },
  { label: 'Five', value: 5, disabled: false },
  { label: 'Six', value: 6, disabled: false },
];

const selectTab = (tab: Tab) => {
  selectedTab.value = tab.value;
  selectionText.value = `Tab "${tab.label}" selected`;
};

// @example-end

// @example-start|string
type TabItem = {
  label: string;
  value: string;
  disabled: boolean;
};

const currentTabItem = ref('');

const selectedTabItem = ref('tab6');

const selectionItemText = ref('Tab "Six" selected');

const tabsItems: TabItem[] = [
  { label: 'One', value: 'tab1', disabled: true },
  { label: 'Two', value: 'tab2', disabled: false },
  { label: 'Three', value: 'tab3', disabled: false },
  { label: 'Four', value: 'tab4', disabled: true },
  { label: 'Five', value: 'tab5', disabled: false },
  { label: 'Six', value: 'tab6', disabled: false },
];

const selectTabItem = (tab: TabItem) => {
  selectedTabItem.value = tab.value;
  selectionItemText.value = `Tab "${tab.label}" selected`;
};
// @example-end
</script>

<style lang="scss"></style>

// packages/csc-ui/documentation/angular/src/app/examples/c-swiper/c-swiper.component.ts
import { Component, OnInit } from '@angular/core';
import { mdiServer } from '@mdi/js';

interface Tab {
  label: string;
  value: string | number;
  disabled: boolean;
}

@Component({
  selector: 'app-c-swiper',
  templateUrl: './c-swiper.component.html',
  styleUrls: ['./c-swiper.component.scss'],
})
export class CSwiperComponent implements OnInit {
  mdiServer = mdiServer;

  // @example-start|basic
  currentTab = '';

  selectedTab = 1;

  selectionText = `Tab "One" selected`;

  tabs = [
    { label: 'One', value: 1, disabled: false },
    { label: 'Two', value: 2, disabled: false },
    { label: 'Three', value: 3, disabled: false },
    { label: 'Four', value: 4, disabled: true },
    { label: 'Five', value: 5, disabled: false },
    { label: 'Six', value: 6, disabled: false },
  ];

  currentTab2 = '';

  selectedTab2 = 'tab6';

  selectionText2 = 'Tab "Six" selected';

  tabs2 = [
    { label: 'One', value: 'tab1', disabled: true },
    { label: 'Two', value: 'tab2', disabled: false },
    { label: 'Three', value: 'tab3', disabled: false },
    { label: 'Four', value: 'tab4', disabled: true },
    { label: 'Five', value: 'tab5', disabled: false },
    { label: 'Six', value: 'tab6', disabled: false },
  ];

  selectTab(tab: Tab) {
    this.selectedTab = tab.value as number;
    this.selectionText = `Tab "${tab.label}" selected`;
  }

  selectTab2(tab: Tab) {
    this.selectedTab2 = tab.value as string;
    this.selectionText2 = `Tab "${tab.label}" selected`;
  }
  // @example-end

  constructor() {}

  ngOnInit(): void {}
}

<app-example title="Usage" name="basic" component="c-swiper">
  <c-swiper [(ngModel)]="currentTab" cControl>
    <c-swiper-tab
      *ngFor="let tab of tabs; let i = index"
      icon="storage"
      [active]="selectedTab === tab.value"
      [label]="tab.label"
      [value]="tab.value"
      [disabled]="tab.disabled"
      (click)="!tab.disabled && selectTab(tab)"
      (keyup.enter)="!tab.disabled && selectTab(tab)"
    >
      <c-icon [path]="mdiServer" slot="icon"></c-icon>

      Lorem ipsum dolor sit amet, consectetur adipiscing elit.

      <span *ngIf="i % 2 === 0">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</span>
    </c-swiper-tab>
  </c-swiper>

  <p class="mt-3">Focused tab: {{ currentTab }}</p>

  <p class="mt-2">Selection: {{ selectionText }}</p>
</app-example>

<app-example title="Usage" name="string" component="c-swiper">
  <c-swiper [(ngModel)]="currentTab2" cControl>
    <c-swiper-tab
      *ngFor="let tab of tabs2; let i = index"
      icon="storage"
      [active]="selectedTab2 === tab.value"
      [label]="tab.label"
      [value]="tab.value"
      [disabled]="tab.disabled"
      (click)="!tab.disabled && selectTab2(tab)"
      (keyup.enter)="!tab.disabled && selectTab2(tab)"
    >
      <c-icon [path]="mdiServer" slot="icon"></c-icon>

      Lorem ipsum dolor sit amet, consectetur adipiscing elit.

      <span *ngIf="i % 2 === 0">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</span>
    </c-swiper-tab>
  </c-swiper>

  <p class="mt-3">Focused tab: {{ currentTab2 }}</p>

  <p class="mt-2">Selection: {{ selectionText2 }}</p>
</app-example>
