// packages/csc-ui-documentation/app/examples/c-autocomplete/small.react.tsx
import { CAutocomplete, COption, COptionValue } from '@cscfi/csc-ui-react';
// @ts-nocheck — documentation code sample; shown as text, never compiled here
import { useState } from 'react';

export const Small = () => {
  const [language, setLanguage] = useState<null | string>(null);

  return (
    <div>
      <CAutocomplete
        label="Programming language"
        onChangeValue={(event) => setLanguage(event.detail as null | string)}
        size="small"
        value={language}
      >
        <COption value="js">
          <COptionValue>JavaScript</COptionValue>
        </COption>
        <COption value="ts">
          <COptionValue>TypeScript</COptionValue>
        </COption>
        <COption value="py">
          <COptionValue>Python</COptionValue>
        </COption>
      </CAutocomplete>
    </div>
  );
};

// packages/csc-ui-documentation/app/examples/c-autocomplete/small.vue
<template>
  <div>
    <c-autocomplete
      v-model="language"
      label="Programming language"
      size="small"
    >
      <c-option value="js">
        <c-option-value>JavaScript</c-option-value>
      </c-option>

      <c-option value="ts">
        <c-option-value>TypeScript</c-option-value>
      </c-option>

      <c-option value="py">
        <c-option-value>Python</c-option-value>
      </c-option>
    </c-autocomplete>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const language = ref<string | null>(null);
</script>
