// packages/csc-ui-documentation/components/examples/COtpInput.vue
<template>
  <component-example name="basic" rows>
    <template #title>Basic usage</template>

    <p>Automatic submitting</p>

    <c-otp-input
      id="basic-otp-example"
      v-model="otp1"
      v-control
      hint="Please enter your one time password"
      @completion="onComplete($event)"
    />

    <p>Manual submitting</p>

    <div>
      <c-otp-input
        id="basic-otp-example"
        v-model="otp2"
        v-control
        hint="Please enter your one time password"
        :length="5"
        :valid="isValid"
        :validation="errorMessage"
      />
      <c-button
        @click="onManualCompletion()"
        @keyup.enter="onManualCompletion()"
      >
        Submit
      </c-button>
    </div>

    <teleport to="body">
      <c-toasts ref="toasts" />
    </teleport>
  </component-example>
</template>

<script setup lang="ts">
// @example-start|basic
import { ref } from 'vue';
import { CToastType } from '@cscfi/csc-ui';

const toasts = ref<HTMLCToastsElement | null>(null);

const otp1 = ref('');

const onComplete = (event: CustomEvent) => {
  toasts.value?.addToast({
    message: `OTP: ${event.detail}`,
    duration: 3000,
    type: CToastType.Success,
  });
};

const otp2 = ref('');
const errorMessage = ref('');
const isValid = ref(true);

const onManualCompletion = () => {
  if (!otp2.value) {
    errorMessage.value = 'Invalid OTP';
    isValid.value = false;

    toasts.value?.addToast({
      message: 'Invalid OTP',
      type: CToastType.Error,
    });

    return;
  }

  errorMessage.value = '';
  isValid.value = true;

  toasts.value?.addToast({
    message: `OTP: ${otp2.value}`,
    type: CToastType.Success,
  });
};
// @example-end
</script>

<style lang="scss"></style>

// packages/csc-ui/documentation/angular/src/app/examples/c-otp-input/c-otp-input.component.ts
import { Component, OnInit } from '@angular/core';
import { CToastType } from '../../../../../../src/types';

@Component({
  selector: 'app-c-otp-input',
  templateUrl: './c-otp-input.component.html',
  styleUrls: ['./c-otp-input.component.scss'],
})
export class COtpInputComponent implements OnInit {
  // @example-start|basic
  otp1 = '';
  // @example-end

  // @example-start|manual
  otp2 = '';

  errorMessage = '';

  valid = true;
  // @example-end

  constructor() {}

  ngOnInit(): void {}

  // @example-start|basic
  onComplete(event) {
    const toasts = document.getElementById('toasts') as HTMLCToastsElement;

    toasts.addToast({
      message: `OTP Code: ${event.detail}`,
      duration: 3000,
      type: CToastType.Success,
    });
  }
  // @example-end

  // @example-start|manual
  onManualCommit() {
    const toasts = document.getElementById('manual-toasts') as HTMLCToastsElement;

    if (!this.otp2) {
      this.errorMessage = 'Invalid OTP Code';
      this.valid = false;

      toasts.addToast({
        message: 'Invalid OTP Code',
        type: CToastType.Error,
      });

      return;
    }

    this.errorMessage = '';
    this.valid = true;

    toasts.addToast({
      message: `OTP Code: ${this.otp2}`,
      type: CToastType.Success,
    });
  }
  // @example-end
}
