// packages/csc-ui-documentation/app/examples/c-checkbox/states.react.tsx
// @ts-nocheck — documentation code sample; shown as text, never compiled here
import { CCheckbox } from '@cscfi/csc-ui-react';

export const States = () => (
  <div className="example-row">
    <CCheckbox hideDetails>Unchecked</CCheckbox>
    <CCheckbox checked hideDetails>
      Checked
    </CCheckbox>
    <CCheckbox indeterminate hideDetails>
      Indeterminate
    </CCheckbox>
    <CCheckbox disabled hideDetails>
      Disabled
    </CCheckbox>
    <CCheckbox checked disabled hideDetails>
      Checked and disabled
    </CCheckbox>
  </div>
);

// packages/csc-ui-documentation/app/examples/c-checkbox/states.vue
<template>
  <div class="example-row">
    <c-checkbox hide-details>Unchecked</c-checkbox>

    <c-checkbox checked hide-details>Checked</c-checkbox>

    <c-checkbox hide-details indeterminate>Indeterminate</c-checkbox>

    <c-checkbox disabled hide-details>Disabled</c-checkbox>

    <c-checkbox checked disabled hide-details>Checked and disabled</c-checkbox>
  </div>
</template>
